#!/usr/bin/env python3
"""Fix 5 missing recipes: 53367, 52875, 52831, 53358, and check for any others."""

import re, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))

FILE = 'src/data/recipes_chunk04.ts'
with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

def escape_for_ts(s):
    return s.replace("\\", "\\\\").replace("'", "\\'")

missing = {}

# 53367: Chicken Fried Rice
missing['53367'] = {
'ro': 'Orezul prajit se face cel mai bine cu orez ramas de cel putin o zi. Altfel devine lipicios in tigaie.\nDaca nu ai orez ramas de seara trecuta, gateste o portie de orez si intinde-l pe o tava mare sau pe mai multe farfurii mari. Lasa orezul sa se usuce circa 1-2 ore inainte de a-l folosi pentru orez prajit.\n\nOrezul se lipeste foarte usor de tigaie, asa ca asigura-te ca folosesti un wok sau o tigaie care nu se lipeste. De obicei gatesc la wok-ul meu din otel carbon, dar tigaile din fonta sau cele antiaderente merg si ele bine. S-ar putea sa fie nevoie sa adaugi putin mai mult ulei daca lucrurile nu se desprind usor.\n\nPregatirea puiului:\nTaie puiul in cuburi mici de 0,5-1 cm. Presara 1/2 lingurita de sare peste pui si amesteca. Pune puiul deoparte circa 10 minute (de obicei folosesc acest timp pentru a toca toate legumele).\n\nOuale jumari:\nIncinge un wok sau o tigaie mare pe foc mare. Toarna o lingura de ulei si adauga ouale batute. Foloseste o spatula pentru a face rapid ouale jumari, rupand bucatile pe masura ce se formeaza. Muta ouale pe o farfurie.\n\nGatirea puiului:\nAdauga o alta lingura de ulei in wok. Adauga puiul si gateste 4-5 minute, amestecand din cand in cand. Opreste focul si muta puiul gatit pe o farfurie.\n\nCu spatula, curata orice bucati de pui ramase lipite de wok ca sa nu se arda la pasul urmator. Poti folosi si servetele de hartie pentru a sterge wok-ul.\n\nGatirea legumelor:\nToarna 1 lingura de ulei in wok pe foc mare. Adauga ceapa taiata cuburi si gateste 1 minut, pana incepe sa se inmoaie. Adauga usturoiul si ghimbirul tocate si gateste pana devine aromat, circa 30 secunde. Adauga morcovii taiati cuburi si gateste 2 minute, amestecand des. Adauga 1/2 lingurita de sare si mazarea si amesteca.\n\nGatirea orezului:\nAdauga orezul in wok peste legume si amesteca. Cu spatula, zdrobeste orice bucati mari de orez pentru a le desface. Adauga partile albe si verzi ale cepei verzi taiate (pastreaza partile verde inchis) si pudra de cinci condimente. Amesteca pentru a incorpora. Daca orezul incepe sa se lipeasca de tigaie, adauga putin mai mult ulei.\n\nStropeste sosul de soia si uleiul de susan peste orez si amesteca. Incorporeaza puiul gatit, ouale jumari si partile inchise la culoare ale cepei verzi. Amesteca scurt pentru a combina totul si gateste inca 1-2 minute.\n\nServire:\nGusteaza si adauga mai mult sos de soia daca e necesar. Serveste imediat.',
'ru': 'Жареный рис лучше всего готовить из оставшегося риса, которому минимум день. Иначе он становится клейким на сковороде.\nЕсли у вас нет вчерашнего риса, приготовьте порцию и разложите на большом противне или нескольких тарелках. Дайте рису подсохнуть около 1-2 часов перед использованием.\n\nРис легко прилипает к сковороде, поэтому используйте вок или сковороду с антипригарным покрытием. Обычно я готовлю в воке из углеродистой стали, но чугунные или антипригарные сковороды тоже подходят. Может понадобиться немного больше масла, если еда прилипает.\n\nПодготовка курицы:\nНарежьте курицу мелкими кубиками по 0,5-1 см. Посыпьте 1/2 чайной ложки соли и перемешайте. Отложите курицу примерно на 10 минут (обычно я использую это время для нарезки овощей).\n\nЯичница:\nРазогрейте вок или большую сковороду на сильном огне. Влейте столовую ложку масла и добавьте взбитые яйца. Быстро перемешайте лопаткой, разбивая комки по мере образования. Переложите яйца на тарелку.\n\nГотовка курицы:\nДобавьте ещё столовую ложку масла в вок. Положите курицу и готовьте 4-5 минут, периодически помешивая. Выключите огонь и переложите готовую курицу на тарелку.\n\nЛопаткой соскребите остатки курицы с вока, чтобы они не подгорели на следующем этапе. Можно также протереть вок бумажными полотенцами.\n\nГотовка овощей:\nВлейте 1 столовую ложку масла в вок на сильном огне. Добавьте нарезанный лук и готовьте 1 минуту, пока он не начнёт размягчаться. Вмешайте измельчённый чеснок и имбирь и готовьте до появления аромата, около 30 секунд. Добавьте нарезанную морковь и готовьте 2 минуты, часто помешивая. Добавьте 1/2 чайной ложки соли и горошек и перемешайте.\n\nГотовка риса:\nДобавьте рис в вок поверх овощей и перемешайте. Тыльной стороной лопатки разомните крупные комки риса. Добавьте белые и зелёные части нарезанного лука (тёмно-зелёные отложите) и порошок пяти специй. Перемешайте. Если рис начинает прилипать, добавьте немного масла.\n\nПолейте рис соевым соусом и кунжутным маслом и перемешайте. Вмешайте готовую курицу, яичницу и тёмные части лука. Кратко перемешайте и готовьте ещё 1-2 минуты.\n\nПодача:\nПопробуйте и добавьте больше соевого соуса при необходимости. Подавайте немедленно.',
'es': 'El arroz frito se hace mejor con arroz sobrante de al menos un dia. De lo contrario se pone pegajoso en la sarten.\nSi no tiene arroz sobrante de la noche anterior, cocine una tanda de arroz y extiendalo en una bandeja grande o varios platos grandes. Deje que el arroz se seque por unas 1-2 horas antes de usarlo para arroz frito.\n\nEl arroz se pega facilmente a la sarten, asi que asegurese de usar un wok o sarten antiadherente. Generalmente cocino en mi wok de acero al carbono, pero las sartenes de hierro fundido o antiadherentes tambien funcionan bien. Podria necesitar agregar un poco mas de aceite si las cosas no se despegan facilmente.\n\nPreparacion del pollo:\nCorte el pollo en cubos pequenos de 0,5-1 cm. Espolvoree 1/2 cucharadita de sal sobre el pollo y mezcle. Reserve el pollo por unos 10 minutos (generalmente uso este tiempo para picar todas las verduras).\n\nRevuelva los huevos:\nCaliente un wok o sarten grande a fuego alto. Vierta una cucharada de aceite y agregue los huevos batidos. Use una espatula para revolver rapidamente los huevos, rompiendo los grumos conforme se formen. Pase los huevos a un plato.\n\nCocine el pollo:\nAgregue otra cucharada de aceite al wok. Agregue el pollo y cocine 4-5 minutos, revolviendo de vez en cuando. Apague el fuego y pase el pollo cocido a un plato.\n\nCon la espatula, raspe los restos de pollo pegados al wok para que no se quemen en el siguiente paso. Tambien puede usar toallas de papel para limpiar el wok.\n\nCocine las verduras:\nVierta 1 cucharada de aceite en el wok a fuego alto. Agregue la cebolla picada y cocine 1 minuto hasta que empiece a ablandarse. Agregue el ajo y jengibre picados y cocine hasta que este aromatico, unos 30 segundos. Agregue las zanahorias picadas y cocine 2 minutos, revolviendo con frecuencia. Agregue 1/2 cucharadita de sal y los guisantes y revuelva.\n\nCocine el arroz:\nAgregue el arroz al wok sobre las verduras y revuelva. Con el reves de la espatula, aplaste los grumos grandes de arroz para deshacerlos. Agregue las partes blancas y verdes de las cebolletas rebanadas (guarde las partes verde oscuro) y el polvo de cinco especias. Revuelva para incorporar. Si el arroz se pega, agregue un poco mas de aceite.\n\nRocie la salsa de soja y el aceite de sesamo sobre el arroz y revuelva. Incorpore el pollo cocido, los huevos revueltos y las partes oscuras de las cebolletas. Revuelva brevemente para combinar y cocine otros 1-2 minutos.\n\nServir:\nPruebe y agregue mas salsa de soja si es necesario. Sirva inmediatamente.',
}

# 52875: Chicken Ham and Leek Pie
missing['52875'] = {
'ro': 'Incinge supa de pui intr-o cratita cu capac. Adauga pieptul de pui si adu la fierbere usoara. Acopera cu capac si gateste 10 minute. Scoate pieptul de pui din apa cu un cleste si pune-l pe o farfurie. Toarna lichidul de gatit intr-o cana mare.\nTopeste 25g de unt intr-o cratita mare cu fund gros pe foc mic. Adauga prazul si caleste usor 2 minute, amestecand din cand in cand pana se inmoaie. Adauga usturoiul si gateste inca un minut. Adauga restul de unt si amesteca faina imediat ce untul s-a topit. Gateste 30 secunde, amestecand constant.\nToarna incet laptele in cratita, putin cate putin, amestecand bine intre fiecare adaugare. Adauga treptat 250ml din supa pastrata si vinul, daca folosesti, amestecand pana cand sosul este neted si usor ingrosat. Adu la fierbere usoara si gateste 3 minute.\nCondimenteaza amestecul dupa gust cu sare si piper negru proaspat macinat. Scoate de pe foc si amesteca smantana. Toarna intr-un bol mare si acopera suprafata sosului cu folie alimentara pentru a preveni formarea unei pelicule. Pune deoparte sa se raceasca.\nPreincalzeste cuptorul la 200C/400F/gaz 6. Pune o tava in cuptor sa se incinga.\nPentru aluat, pune faina si untul intr-un robot de bucatarie si mixeaza pe pulsuri pana amestecul seamana cu pesmetul fin. Cu motorul pornit, adauga oul batut si apa si mixeaza pana formeaza o bila. Separa 250g de aluat pentru capac.\nIntinde restul de aluat pe o suprafata usor infainata, intorcand aluatul des pana are circa 5mm grosime si este cu 4cm mai mare decat tava. Ridica aluatul peste sucitorul si aseaza-l delicat in tava. Apasa aluatul ferm pe margini, asigurandu-te ca nu sunt bule de aer. Lasa aluatul in exces sa depaseasca marginile.\nTaie pieptul de pui in bucati de 3cm. Amesteca puiul, sunca si prazul in sosul racit. Toarna umplutura in tava. Unge marginea tavii cu ou batut. Intinde aluatul pastrat pentru capac.\nAcopera placinta cu capacul de aluat si apasa marginile ferm pentru a sigila. Taie orice aluat in exces.\nFa o mica gaura in centrul placintei cu varful unui cutit. Glazureaza suprafata cu ou batut. Coace pe tava preincalzita in centrul cuptorului 35-40 minute sau pana cand placinta este auriu-rumenita si umplutura este foarte fierbinte.',
'ru': 'Нагрейте куриный бульон в кастрюле с крышкой. Добавьте куриную грудку и доведите до слабого кипения. Накройте крышкой и варите 10 минут. Достаньте куриные грудки из воды щипцами и положите на тарелку. Перелейте бульон в большой кувшин.\nРастопите 25g масла в большой кастрюле с толстым дном на слабом огне. Добавьте лук-порей и тушите 2 минуты, периодически помешивая, до мягкости. Добавьте чеснок и готовьте ещё минуту. Добавьте оставшееся масло и вмешайте муку сразу после таяния масла. Готовьте 30 секунд, постоянно помешивая.\nМедленно влейте молоко в кастрюлю, понемногу, хорошо перемешивая между добавлениями. Постепенно добавьте 250ml отложенного бульона и вино, если используете, помешивая до гладкости и лёгкого загустения соуса. Доведите до слабого кипения и варите 3 минуты.\nПриправьте смесь по вкусу солью и свежемолотым чёрным перцем. Снимите с огня и вмешайте сливки. Перелейте в большую миску и накройте поверхность соуса пищевой плёнкой. Отставьте остывать.\nРазогрейте духовку до 200C/400F/газ 6. Поставьте противень в духовку нагреваться.\nДля теста положите муку и масло в кухонный комбайн и измельчите в режиме пульса до состояния мелкой крошки. На работающем моторе добавьте взбитое яйцо и воду и месите до образования шара. Отделите 250g теста для крышки.\nРаскатайте оставшееся тесто на слегка присыпанной мукой поверхности до толщины около 5mm и на 4cm больше формы. Уложите тесто в форму. Прижмите по бокам, убедившись, что нет воздушных пузырей. Оставьте тесто свисать по краям.\nНарежьте куриные грудки на кусочки по 3cm. Вмешайте курицу, ветчину и лук-порей в остывший соус. Вылейте начинку в форму. Смажьте край формы взбитым яйцом. Раскатайте отложенное тесто для крышки.\nНакройте пирог крышкой из теста и прижмите края для герметичности. Обрежьте лишнее тесто.\nСделайте небольшое отверстие в центре пирога кончиком ножа. Смажьте верх взбитым яйцом. Выпекайте на разогретом противне в центре духовки 35-40 минут или пока пирог не станет золотисто-коричневым и начинка не будет горячей.',
'es': 'Caliente el caldo de pollo en una cacerola con tapa. Agregue la pechuga de pollo y lleve a fuego lento. Cubra con la tapa y cocine por 10 minutos. Retire las pechugas del agua con pinzas y coloquelas en un plato. Vierta el liquido de coccion en una jarra grande.\nDerrita 25g de mantequilla en una cacerola grande de fondo grueso a fuego lento. Agregue los puerros y sofria suavemente por 2 minutos, revolviendo de vez en cuando hasta que se ablanden. Agregue el ajo y cocine un minuto mas. Agregue la mantequilla restante e incorpore la harina tan pronto como la mantequilla se derrita. Cocine por 30 segundos, revolviendo constantemente.\nVierta lentamente la leche en la cacerola, poco a poco, revolviendo bien entre cada adicion. Agregue gradualmente 250ml del caldo reservado y el vino, si lo usa, revolviendo hasta que la salsa este suave y ligeramente espesa. Lleve a un hervor suave y cocine por 3 minutos.\nSazone al gusto con sal y pimienta negra recien molida. Retire del fuego e incorpore la crema. Vierta en un tazon grande y cubra la superficie de la salsa con plastico adherente. Reserve para enfriar.\nPrecaliente el horno a 200C/400F/gas 6. Coloque una bandeja en el horno para calentar.\nPara la masa, ponga la harina y la mantequilla en un procesador y pulse hasta que parezca migas finas. Con el motor encendido, agregue el huevo batido y el agua y mezcle hasta que forme una bola. Separe 250g de masa para la tapa.\nEstire la masa restante sobre una superficie ligeramente enharinada hasta unos 5mm de grosor y 4cm mas grande que el molde. Coloquela suavemente en el molde. Presione por los lados, sin dejar burbujas de aire. Deje que el exceso cuelgue por los bordes.\nCorte las pechugas en piezas de 3cm. Mezcle el pollo, el jamon y los puerros en la salsa enfriada. Vierta el relleno en el molde. Unte el borde con huevo batido. Estire la masa reservada para la tapa.\nCubra el pastel con la tapa de masa y presione los bordes para sellar. Recorte el exceso de masa.\nHaga un pequeno agujero en el centro con la punta de un cuchillo. Glasee con huevo batido. Hornee en la bandeja precalentada en el centro del horno por 35-40 minutos o hasta que este dorado y el relleno este caliente.',
}

# 52831: Chicken Karaage
missing['52831'] = {
'ro': 'Adauga ghimbirul, usturoiul, sosul de soia, sake si zaharul intr-un bol si amesteca cu un tel. Adauga puiul si amesteca pentru a-l acoperi uniform. Acopera si pune la frigider cel putin 1 ora.\n\nAdauga 2-3 cm de ulei vegetal intr-o oala cu fund gros si incinge pana cand uleiul ajunge la 180 grade C. Tapeteaza un gratar cu 2 straturi de servetele de hartie si pregateste un cleste. Pune amidonul de cartofi intr-un bol.\n\nAdauga o mana de pui in amidonul de cartofi si amesteca pentru a acoperi fiecare bucata uniform.\n\nPrajeste karaage in serii pana cand exteriorul este maro-mediu si puiul este gatit complet. Muta puiul prajit pe gratarul cu servetele. Daca vrei ca karaage sa ramana crocant mai mult, poti praji puiul a doua oara, pana devine mai inchis la culoare, dupa ce s-a racit o data. Serveste cu felii de lamaie.',
'ru': 'Добавьте имбирь, чеснок, соевый соус, саке и сахар в миску и взбейте венчиком. Добавьте курицу и перемешайте для равномерного покрытия. Накройте и уберите в холодильник минимум на 1 час.\n\nНалейте 2-3 см растительного масла в кастрюлю с толстым дном и нагрейте до 180 градусов C. Застелите решётку 2 слоями бумажных полотенец и приготовьте щипцы. Насыпьте картофельный крахмал в миску.\n\nДобавьте горсть курицы в крахмал и обваляйте каждый кусочек равномерно.\n\nОбжарьте караагэ партиями до средне-коричневого цвета снаружи и полной готовности внутри. Переложите жареную курицу на решётку с полотенцами. Если хотите, чтобы караагэ оставалось хрустящим дольше, можно обжарить курицу второй раз до более тёмного цвета после остывания. Подавайте с дольками лимона.',
'es': 'Agregue el jengibre, el ajo, la salsa de soja, el sake y el azucar a un tazon y bata con un batidor. Agregue el pollo y revuelva para cubrirlo uniformemente. Cubra y refrigere por al menos 1 hora.\n\nAgregue 2-3 cm de aceite vegetal a una olla de fondo grueso y caliente hasta que el aceite alcance 180 grados C. Forre una rejilla con 2 capas de toallas de papel y prepare unas pinzas. Ponga el almidon de papa en un tazon.\n\nAgregue un punado de pollo al almidon de papa y revuelva para cubrir cada pieza uniformemente.\n\nFria el karaage en tandas hasta que el exterior este medianamente dorado y el pollo este cocido por completo. Pase el pollo frito a la rejilla con toallas. Si quiere que el karaage se mantenga crujiente mas tiempo, puede freir el pollo una segunda vez hasta que este mas oscuro despues de enfriarse. Sirva con rodajas de limon.',
}

# 53358: Chicken Mandi
missing['53358'] = {
'ro': '1. Curata si taie puiul; marineaza-l scurt cu sare, turmeric si putin ulei.\n2. Clateste si inmoaie orezul basmati 20-30 minute.\n3. Intr-o oala mare, incinge ghee/uleiul. Prajeste ceapa tocata pana se rumeneste. Adauga usturoiul tocat si ardeii iuti verzi si prajeste 1-2 minute.\n4. Adauga condimentele intregi (cardamom, cuisoare, scortisoara, frunze de dafin) si condimentele macinate (coriandru, chimion). Amesteca pana devin aromate.\n5. Adauga bucatile de pui, rumeneste usor si adauga suficienta apa/supa de pui sa le acopere. Fierbe la foc mic pana cand puiul este aproape gatit.\n6. Scoate puiul; masoara lichidul ramas si adauga orezul inmuiat. Adu la fierbere, apoi reduce focul, acopera si gateste orezul pana este aproape gata.\n7. Pune puiul inapoi in oala cu orez deasupra, acopera bine si abureste pe foc mic 10-15 minute pentru ca aromele sa se combine.\n8. (Optional) Pentru aroma autentica de fum: incinge un carbune mic pana devine rosu, aseaza-l pe o cana mica de folie in centrul oalei, adauga o lingurita de unt/ulei pe carbune apoi acopera imediat pentru a retine fumul 5-10 minute. Scoate carbunele.\n9. Garnieste cu ceapa prajita, coriandru tocat si serveste cu chutney sau raita.\n',
'ru': '1. Очистите и нарежьте курицу; кратко замаринуйте солью, куркумой и небольшим количеством масла.\n2. Промойте и замочите рис басмати на 20-30 минут.\n3. В большой кастрюле нагрейте масло гхи/растительное масло. Обжарьте рубленый лук до золотистого цвета. Добавьте измельчённый чеснок и зелёный чили и жарьте 1-2 минуты.\n4. Добавьте цельные специи (кардамон, гвоздику, корицу, лавровые листья) и молотые специи (кориандр, тмин). Помешивайте до появления аромата.\n5. Добавьте кусочки курицы, слегка подрумяньте и залейте достаточным количеством воды/бульона. Тушите, пока курица почти не приготовится.\n6. Достаньте курицу; отмерьте оставшуюся жидкость и добавьте замоченный рис. Доведите до кипения, затем уменьшите огонь, накройте и варите рис до почти полной готовности.\n7. Верните курицу в кастрюлю с рисом сверху, плотно накройте и тушите на слабом огне 10-15 минут, чтобы вкусы соединились.\n8. (По желанию) Для аутентичного дымного аромата: раскалите маленький уголёк докрасна, поместите на маленькую чашку из фольги в центр кастрюли, капните чайную ложку масла на уголь и сразу накройте, чтобы удержать дым на 5-10 минут. Уберите уголь.\n9. Украсьте жареным луком, рубленой кинзой и подавайте с чатни или раитой.\n',
'es': '1. Limpie y corte el pollo; marine brevemente con sal, curcuma y un poco de aceite.\n2. Enjuague y remoje el arroz basmati 20-30 minutos.\n3. En una olla grande, caliente el ghee/aceite. Fria la cebolla picada hasta dorarla. Agregue el ajo picado y los chiles verdes y fria 1-2 minutos.\n4. Agregue las especias enteras (cardamomo, clavos, canela, hojas de laurel) y las especias molidas (cilantro, comino). Revuelva hasta que esten aromaticas.\n5. Agregue las piezas de pollo, dore ligeramente y agregue suficiente agua/caldo de pollo para cubrir. Cocine a fuego lento hasta que el pollo este casi cocido.\n6. Retire el pollo; mida el liquido restante y agregue el arroz remojado. Lleve a ebullicion, luego reduzca el fuego, cubra y cocine el arroz hasta que este casi listo.\n7. Regrese el pollo a la olla con arroz encima, cubra bien y cocine al vapor a fuego lento 10-15 minutos para que los sabores se mezclen.\n8. (Opcional) Para un aroma ahumado autentico: caliente un pequeno carbon hasta que este al rojo vivo, coloquelo en una taza pequena de papel aluminio en el centro de la olla, agregue una cucharadita de mantequilla/aceite sobre el carbon y cubra inmediatamente para atrapar el humo por 5-10 minutos. Retire el carbon.\n9. Decore con cebollas fritas, cilantro picado y sirva con chutney o raita.\n',
}

# Now apply these to the file
replaced = 0
for recipe_id, trans in missing.items():
    id_pattern = f"id: '{recipe_id}'"
    id_pos = content.find(id_pattern)
    if id_pos == -1:
        print(f"WARNING: Recipe {recipe_id} not found!")
        continue

    instr_pos = content.find("instructions: {", id_pos)
    if instr_pos == -1:
        continue

    for lang in ['ro', 'ru', 'es']:
        if lang not in trans:
            continue
        new_value = escape_for_ts(trans[lang])
        lang_pattern = f" {lang}: '"
        lang_pos = content.find(lang_pattern, instr_pos)
        if lang_pos == -1:
            lang_pattern = f"{lang}: '"
            lang_pos = content.find(lang_pattern, instr_pos)
        if lang_pos == -1:
            continue

        next_id_pos = content.find("id: '", id_pos + len(id_pattern))
        if next_id_pos != -1 and lang_pos > next_id_pos:
            continue

        value_start = content.find("'", lang_pos + len(lang) + 1) + 1
        pos = value_start
        while pos < len(content):
            if content[pos] == "'" and content[pos-1] != '\\':
                break
            if content[pos] == "'" and pos >= 2 and content[pos-2:pos] == '\\\\':
                break
            pos += 1
        value_end = pos
        content = content[:value_start] + new_value + content[value_end:]
        replaced += 1

print(f"Fixed {replaced} additional instruction translations")

with open(FILE, 'w', encoding='utf-8') as f:
    f.write(content)

print("File updated with missing recipes!")
