#!/usr/bin/env python3
"""Part 6: Final recipes + name fixes"""

translations_p6 = {}

# 52788: Christmas Pudding Flapjack
translations_p6['52788'] = {
'ro': 'Preincalzeste cuptorul la 180°C/ventilator 160°C/gaz 4, unge si tapeteaza o tava de 25cm x 20cm. Topeste untul, zaharul, siropul si coaja de portocala intr-o cratita mare la foc mediu. Scopul e sa dizolvi toate ingredientele pana sunt netede, dar sa nu pierzi volum prin fierbere, asa ca ai grija sa nu supraincalzesti.\n\nAdauga fulgii de ovaz si amesteca bine pana sunt acoperiti uniform. Amesteca budinca de Craciun ramasa si pune in tava pregatita. Foloseste o lingura sa nivelezi si coace 40 minute pana marginile incep sa se rumeneasca. Cat e inca calda in tava, cresta in 12 patrate. Lasa sa se raceasca complet inainte de a taia de-a lungul crestaturii.\n\nSe pastreaza 5 zile intr-o cutie etansa sau se congeleaza pana la 1 luna.',
'ru': 'Разогрейте духовку до 180°C/вентилятор 160°C/газ 4, смажьте и застелите форму 25cm x 20cm. Растопите масло, сахар, сироп и апельсиновую цедру в большой кастрюле на среднем огне. Цель - растворить все ингредиенты до однородности, но не потерять объём от кипения, поэтому не перегревайте.\n\nДобавьте овсяные хлопья и хорошо перемешайте до равномерного покрытия. Вмешайте оставшийся рождественский пудинг и выложите в подготовленную форму. Разровняйте ложкой и выпекайте 40 минут, пока края не начнут румяниться. Пока ещё тёплое в форме, надрежьте на 12 квадратов. Дайте полностью остыть перед нарезкой по надрезам.\n\nХранится 5 дней в герметичной ёмкости или замораживается до 1 месяца.',
'es': 'Precaliente el horno a 180°C/ventilador 160°C/gas 4, engrase y forre un molde de 25cm x 20cm. Derrita la mantequilla, el azucar, el jarabe y la ralladura de naranja en una cacerola grande a fuego medio. El objetivo es disolver todos los ingredientes hasta que queden suaves, pero no perder volumen por hervor, asi que tenga cuidado de no sobrecalentar.\n\nAgregue los copos de avena y revuelva bien hasta que esten cubiertos uniformemente. Incorpore el pudin de Navidad sobrante y vierta en el molde preparado. Use una cuchara para aplanar y hornee por 40 minutos hasta que los bordes empiecen a dorarse. Mientras aun este tibio en el molde, marque en 12 cuadros. Deje enfriar completamente antes de cortar por las marcas.\n\nSe conserva por 5 dias en un recipiente hermetico o se congela hasta 1 mes.',
}

# 52989: Christmas Pudding Trifle
translations_p6['52989'] = {
'ro': 'Curata portocalele cu un cutit ascutit, asigurandu-te ca s-a scos toata pielea alba. Feliaza cat mai subtire si aseaza pe o farfurie. Presara zaharul demerara urmat de Grand Marnier si pune deoparte.\n\nSfarama budinca de Craciun in bucati mari si imprastie pe fundul unui bol de trifle. Aseaza portocalele peste budinca intr-un strat si toarna orice sucuri ramase.\n\nBate mascarpone pana devine neted, apoi amesteca crema de vanilie. Pune amestecul peste portocale.\n\nBate usor smantana si pune peste crema. Presara migdalele fulgi si ciocolata rasa. Poti face asta cu o zi inainte, pune la rece pana la servire.',
'ru': 'Очистите апельсины острым ножом, убедившись, что вся белая часть удалена. Нарежьте как можно тоньше и разложите на обеденной тарелке. Посыпьте сахаром демерара, затем полейте Grand Marnier и отставьте.\n\nРаскрошите рождественский пудинг крупными кусками и разложите по дну миски для трайфла. Уложите апельсины поверх пудинга в один слой и полейте оставшимся соком.\n\nВзбейте маскарпоне до однородности, затем вмешайте заварной крем. Выложите смесь поверх апельсинов.\n\nСлегка взбейте сливки и выложите поверх крема. Посыпьте миндальными хлопьями и тёртым шоколадом. Можно приготовить за день, хранить в холодильнике до подачи.',
'es': 'Pele las naranjas con un cuchillo afilado, asegurandose de que toda la parte blanca este retirada. Corte lo mas delgado posible y acomode sobre un plato. Espolvoree con el azucar demerara seguido del Grand Marnier y reserve.\n\nDesmenuce el pudin de Navidad en trozos grandes y esparza sobre el fondo de un tazon para trifle. Coloque las naranjas sobre el pudin en una capa y vierta los jugos restantes.\n\nBata el mascarpone hasta que quede suave, luego incorpore las natillas. Ponga la mezcla sobre las naranjas.\n\nBata ligeramente la crema y ponga sobre las natillas. Espolvoree con las almendras laminadas y el chocolate rallado. Puede hacerlo un dia antes si lo desea, refrigere hasta servir.',
}

# 53283: Chtitha Batata
translations_p6['53283'] = {
'ro': 'Combina usturoiul, ardeiul iute, chimionul, boia, piperul negru, piperul cayenne si sarea intr-un mojar; macina cu pistilul pana formeaza o pasta. Adauga uleiul de masline si amesteca dersa bine.\n\nIncinge o cratita mare la foc mediu si caleste dersa pana devine aromata, 2-4 minute. Adauga jumatati de cartofi si amesteca sa se combine cu dersa. Amesteca pasta de tomate. Toarna suficienta apa cat sa acopere cartofii si adu la fierbere. Reduce focul si fierbe la foc mic pana cand cartofii sunt fragezi, circa 40 minute.\n\nPune cartofii intr-un bol de servire. Adauga orice sos ramas peste cartofi.',
'ru': 'Соедините чеснок, чили, тмин, паприку, чёрный перец, кайенский перец и соль в ступке; разотрите пестиком до пастообразного состояния. Добавьте оливковое масло и хорошо перемешайте дерсу.\n\nНагрейте большую кастрюлю на среднем огне и обжарьте дерсу до появления аромата, 2-4 минуты. Добавьте половинки картофеля и перемешайте с дерсой. Вмешайте томатную пасту. Влейте достаточно воды, чтобы едва покрыть картофель, и доведите до кипения. Уменьшите огонь и тушите, пока картофель не станет мягким, около 40 минут.\n\nВыложите картофель в сервировочную миску. Полейте оставшимся соусом.',
'es': 'Combine el ajo, el chile, el comino, el pimenton, la pimienta negra, la pimienta de cayena y la sal en un mortero; muela con el pistilo hasta formar una pasta. Agregue el aceite de oliva y mezcle bien la dersa.\n\nCaliente una olla grande a fuego medio y saltee la dersa hasta que este aromatica, 2-4 minutos. Agregue las mitades de papa y revuelva para combinar con la dersa. Incorpore la pasta de tomate. Vierta suficiente agua para apenas cubrir las papas y lleve a ebullicion. Reduzca el fuego y cocine a fuego lento hasta que las papas esten tiernas, unos 40 minutos.\n\nSirva las papas en un tazon. Ponga cualquier salsa restante sobre las papas.',
}

# 53153: Churros
translations_p6['53153'] = {
'ro': 'Pasul 1\nFierbe apa, apoi masoara 300ml apa clocotita intr-o cana si adauga untul topit si extractul de vanilie. Cerne faina si praful de copt intr-un bol mare cu un varf generos de sare. Fa un put in centru, apoi toarna continutul canii si bate foarte repede in faina cu o lingura de lemn pana nu mai are cocoloase. Odihneste 10-15 minute in timp ce faci sosul.\n\nPasul 2\nPune toate ingredientele de sos intr-o cratita si topeste-le impreuna usor, amestecand din cand in cand pana obtii un sos neted si lucios. Tine cald la foc mic.\n\nPasul 3\nUmple o cratita mare adanca pana la o treime cu ulei. Incalzeste pana cand un cub de paine se rumeneste in 45 secunde - 1 minut. Acopera o tava cu servetele de hartie si amesteca zaharul pudra fin cu scortisoara.\n\nPasul 4\nMonteaza un dui stea pe un pos - 1,5-2cm latime e o marime buna. Umple cu aluatul odihnit, apoi formeaza 2-3 benzi direct in ulei, taiand capatul fiecareia cu foarfeca. Formeaza patru-cinci la un moment dat si prajeste pana se rumenesc si devin crocante. Fii foarte atent - daca se formeaza bule de aer in churros pot exploda, mai ales daca uleiul se supraincalzeste.\n\nPasul 5\nCand churros sunt crocanti si aurii, scoate-le din ulei cu o lingura cu gauri si scurge pe tava cu servetele. Continua sa gatesti restul aluatului in serii, presarand zahar cu scortisoara pe churros pe masura. Cand ai gatit toti churros, rostogoleste-i in zaharul cu scortisoara ramas si serveste cu sosul de ciocolata pentru inmuiere.\nPentru a vedea un video despre cum sa pregatesti churros, vezi reteta noastra de sandvis de inghetata cu churros.',
'ru': 'Шаг 1\nВскипятите чайник, затем отмерьте 300ml кипятка в кувшин и добавьте растопленное масло и ванильный экстракт. Просейте муку и разрыхлитель в большую миску со щедрой щепоткой соли. Сделайте углубление в центре, влейте содержимое кувшина и очень быстро вмешайте в муку деревянной ложкой до однородности. Дайте отдохнуть 10-15 минут, пока готовите соус.\n\nШаг 2\nПоложите все ингредиенты для соуса в кастрюлю и осторожно растопите вместе, периодически помешивая, до получения гладкого блестящего соуса. Держите тёплым на слабом огне.\n\nШаг 3\nНаполните большую глубокую кастрюлю маслом на треть. Нагрейте, пока кубик хлеба не подрумянится за 45 секунд - 1 минуту. Застелите поднос бумажными полотенцами и смешайте мелкий сахар с корицей.\n\nШаг 4\nУстановите звёздочную насадку на кондитерский мешок - 1,5-2cm шириной хороший размер. Наполните отдохнувшим тестом, затем выдавите полоски по 2-3 штуки прямо в масло, отрезая конец каждой ножницами. Жарьте по четыре-пять штук до золотисто-коричневого и хрустящего состояния. Будьте очень осторожны - если в чуррос образуются пузырьки воздуха, они могут лопнуть, особенно если масло перегрето.\n\nШаг 5\nКогда чуррос хрустящие и золотистые, достаньте шумовкой и выложите на бумажные полотенца. Продолжайте жарить остальное тесто партиями, посыпая готовые чуррос коричным сахаром. Когда все чуррос готовы, обваляйте в оставшемся коричном сахаре и подавайте с шоколадным соусом для макания.\nЧтобы посмотреть видео о приготовлении чуррос, смотрите наш рецепт сэндвича-мороженого с чуррос.',
'es': 'Paso 1\nHierva agua, luego mida 300ml de agua hirviendo en una jarra y agregue la mantequilla derretida y el extracto de vainilla. Tamice la harina y el polvo de hornear en un tazon grande con una pizca generosa de sal. Haga un pozo en el centro, vierta el contenido de la jarra y bata muy rapido en la harina con una cuchara de madera hasta que no tenga grumos. Deje reposar 10-15 minutos mientras hace la salsa.\n\nPaso 2\nPonga todos los ingredientes de la salsa en una olla y derritalos juntos suavemente, revolviendo de vez en cuando hasta tener una salsa suave y brillante. Mantenga tibio a fuego lento.\n\nPaso 3\nLlene una olla grande y profunda hasta un tercio con aceite. Caliente hasta que un cubo de pan se dore en 45 segundos a 1 minuto. Cubra una bandeja con toallas de papel y mezcle el azucar fino con la canela.\n\nPaso 4\nColoque una boquilla de estrella en una manga pastelera - 1,5-2cm de ancho es un buen tamano. Llene con la masa reposada, luego forme tiras de 2-3 directamente en el aceite, cortando el extremo con tijeras. Haga cuatro o cinco a la vez y fria hasta que esten dorados y crujientes. Tenga mucho cuidado - si se forman burbujas de aire en los churros pueden explotar, especialmente si el aceite se sobrecalienta.\n\nPaso 5\nCuando los churros esten crujientes y dorados, retirelos del aceite con una cuchara ranurada y escurra sobre las toallas de papel. Continue cocinando el resto de la masa en tandas, espolvoreando los churros cocidos con azucar con canela. Cuando haya cocinado todos los churros, ruedelos en el azucar con canela restante y sirva con la salsa de chocolate para mojar.\nPara ver un video de como preparar churros, vea nuestra receta de sandwich de helado con churros.',
}

# 53116: Cinnamon buns
translations_p6['53116'] = {
'ro': 'Intr-o cratita mica incalzeste untul, laptele si sarea pana se topeste untul. Lasa amestecul sa se raceasca pana e caldut.\n\nIntr-un bol mare, amesteca fainurile, drojdia, cardamomul si zaharul pana se combina.\n\nFa un put in centru si sparge ouale. Toarna amestecul de lapte caldut si amesteca totul pentru a forma un aluat lipicios. S-ar putea sa fie nevoie sa folosesti mainile pe masura ce aluatul devine mai tare.\n\nUnge suprafata de lucru cu o lingurita de ulei de masline. Rastoarna aluatul pe suprafata si framanta energic 5-8 minute, folosind o racleta dupa nevoie. Nu fi tentat sa adaugi faina, va face chiflele uscate si tari. Framanta pana aluatul e considerabil mai putin lipicios, mai neted si mai elastic.\n\nModeleaza intr-o bila si pune intr-un bol mare uns. Acopera cu un prosop curat si pune intr-un loc cald sa creasca o ora, sau pana se dubleaza.\n\nIntre timp, pentru umplutura si topping, amesteca untul inmuiat intr-un bol cu jumatate din zahar si 1 lingura de scortisoara. Foloseste o furculita sa amesteci zaharul si condimentul in unt pana se combina complet.\n\nAmesteca restul de zahar si scortisoara intr-un bol separat si pune deoparte.\n\nCand aluatul a crescut, rastoarna pe o suprafata infainata si intinde usor intr-un dreptunghi de 36x24cm. Intinde untul cu scortisoara si zahar uniform pe aluat cu un cutit.\n\nCu marginea cea mai lunga spre tine, ruleaza aluatul intr-un cilindru. Taie in 12 felii egale.\n\nAseaza fiecare felie pe o forma de briosa pe o tava, sau intr-o forma de muffin unsa. (Coacerea intr-o forma de muffin va face chiflele mai inalte si bombate.)\n\nAcopera cu un prosop curat si pune deoparte sa creasca din nou 30-45 minute, sau pana cresc.\n\nPreincalzeste cuptorul la 200C/180C ventilator/gaz 6.\n\nUnge varfurile chiflelor cu ou batut si presara generos cu zahar cu scortisoara. Coace 12 minute pana chiflele sunt maro-inchis aurii. Savureaza calde cu o cana de cafea.',
'ru': 'В маленькой кастрюле нагрейте масло, молоко и соль, пока масло не растает. Дайте смеси остыть до тёплого состояния.\n\nВ большой миске смешайте муку, дрожжи, кардамон и сахар.\n\nСделайте углубление в центре и разбейте яйца. Влейте тёплую молочную смесь и перемешайте всё для образования липкого теста. Возможно, придётся работать руками, когда тесто станет плотнее.\n\nСмажьте рабочую поверхность чайной ложкой оливкового масла. Выложите тесто и энергично вымешивайте 5-8 минут, используя скребок при необходимости. Не поддавайтесь искушению добавить муку - булочки станут сухими и жёсткими. Месите, пока тесто не станет значительно менее липким, более гладким и эластичным.\n\nСформируйте шар и положите в большую смазанную миску. Накройте чистым полотенцем и поставьте в тёплое место для подъёма на час или до удвоения.\n\nТем временем для начинки и посыпки смешайте размягчённое масло в миске с половиной сахара и 1 столовой ложкой корицы. Вилкой вмешайте сахар и специю в масло до полного объединения.\n\nСмешайте оставшийся сахар и корицу в отдельной миске и отставьте.\n\nКогда тесто поднялось, выложите на присыпанную мукой поверхность и аккуратно раскатайте в прямоугольник 36x24cm. Распределите масло с корицей и сахаром равномерно по тесту ножом.\n\nДлинной стороной к себе сверните тесто в цилиндр. Нарежьте на 12 равных частей.\n\nПоложите каждый кусочек на бумажную формочку для капкейков на противне или в смазанную форму для маффинов. (Выпечка в форме для маффинов сделает булочки выше и куполообразными.)\n\nНакройте чистым полотенцем и дайте подняться ещё 30-45 минут.\n\nРазогрейте духовку до 200C/180C вентилятор/газ 6.\n\nСмажьте верхушки булочек взбитым яйцом и щедро посыпьте коричным сахаром. Выпекайте 12 минут до тёмно-золотистого цвета. Наслаждайтесь тёплыми с чашкой кофе.',
'es': 'En una olla pequena caliente la mantequilla, la leche y la sal hasta que la mantequilla se derrita. Deje que la mezcla se enfrie hasta que este tibia.\n\nEn un tazon grande, mezcle las harinas, la levadura, el cardamomo y el azucar.\n\nHaga un pozo en el centro y rompa los huevos. Vierta la mezcla de leche tibia y revuelva todo para formar una masa pegajosa. Puede que tenga que usar las manos cuando la masa se ponga mas firme.\n\nEngrase la superficie de trabajo con una cucharadita de aceite de oliva. Voltee la masa y amase vigorosamente por 5-8 minutos, usando un raspador si es necesario. No se tiente a agregar harina, hara los bollitos secos y duros. Amase hasta que la masa este considerablemente menos pegajosa, mas suave y elastica.\n\nForme una bola y ponga en un tazon grande engrasado. Cubra con un pano limpio y deje en un lugar tibio para leudar por una hora o hasta que duplique su tamano.\n\nMientras tanto, para el relleno y la cobertura, mezcle la mantequilla ablandada en un tazon con la mitad del azucar y 1 cucharada de canela. Use un tenedor para mezclar el azucar y la especia en la mantequilla hasta combinar completamente.\n\nMezcle el azucar y canela restantes en un tazon aparte y reserve.\n\nCuando la masa haya subido, voltee sobre una superficie enharinada y estire suavemente en un rectangulo de 36x24cm. Extienda la mantequilla con canela y azucar uniformemente sobre la masa con un cuchillo.\n\nCon el borde mas largo hacia usted, enrolle la masa en un cilindro. Corte en 12 rebanadas iguales.\n\nColoque cada rebanada sobre un capacillo de cupcake en una bandeja, o en un molde para muffins engrasado. (Hornear en un molde para muffins hara los bollitos mas altos y con forma de domo.)\n\nCubra con un pano limpio y deje leudar nuevamente por 30-45 minutos o hasta que suban.\n\nPrecaliente el horno a 200C/180C ventilador/gas 6.\n\nUnte las partes superiores de los bollitos con huevo batido y espolvoree generosamente con azucar con canela. Hornee por 12 minutos hasta que esten de color dorado oscuro. Disfrute tibios con una taza de cafe.',
}

# 52840: Clam chowder
translations_p6['52840'] = {
'ro': 'Clateste scoicile in mai multe schimburi de apa rece si scurge bine. Pune scoicile intr-o oala mare cu 500ml de apa. Acopera, adu la fierbere si fierbe 2 minute pana se deschid. Toarna continutul oalei intr-o strecuratoare peste un bol pentru a prinde supa de scoici. Cand sunt suficient de reci, scoate scoicile din cochilii - pastreaza cateva cochilii goale pentru prezentare daca doresti. Strecoara supa de scoici intr-o cana, lasand orice nisip pe fundul bolului. Ar trebui sa ai circa 800ml supa.\nIncinge untul in aceeasi oala si prajeste baconul 3-4 minute pana incepe sa se rumeneasca. Adauga ceapa, cimbrul si dafin si caleste totul usor 10 minute pana ceapa e moale si aurie. Presara faina si amesteca pentru a forma o pasta, gateste inca 2 minute, apoi adauga treptat supa de scoici, laptele si smantana.\nAdauga cartofii, adu totul la fierbere si lasa sa fiarba usor 10 minute sau pana cartofii sunt gatiti. Foloseste o furculita sa zdrobesti cateva bucati de cartofi de marginea oalei pentru a ingrosa - totusi vrei multe bucati definite. Amesteca carnea de scoici si cateva cochilii, daca ai ales asa, si fierbe un minut sa se reincalzeasca. Condimenteaza cu mult piper negru si putina sare daca e nevoie, apoi amesteca patrunjelul chiar inainte de a servi in boluri sau chifle crocante golite.',
'ru': 'Промойте моллюсков в нескольких сменах холодной воды и хорошо слейте. Положите моллюсков в большую кастрюлю с 500ml воды. Накройте, доведите до кипения и варите 2 минуты, пока не откроются. Вылейте содержимое кастрюли в дуршлаг над миской, чтобы собрать бульон. Когда остынут достаточно, извлеките моллюсков из раковин - сохраните горсть пустых раковин для презентации, если хотите. Процедите бульон в кувшин, оставив осадок на дне миски. Должно получиться около 800ml бульона.\nРастопите масло в той же кастрюле и обжарьте бекон 3-4 минуты до начала румянения. Добавьте лук, тимьян и лавровый лист и тушите 10 минут до мягкости и золотистости лука. Посыпьте мукой и вмешайте для образования пасты, готовьте ещё 2 минуты, затем постепенно вмешайте бульон, молоко и сливки.\nДобавьте картофель, доведите до кипения и тушите 10 минут или до готовности картофеля. Вилкой раздавите несколько кусочков картофеля о стенку кастрюли для загущения - но оставьте много целых кусков. Вмешайте мясо моллюсков и несколько раковин, если выбрали этот вариант, и потушите минуту для прогрева. Приправьте чёрным перцем и немного солью при необходимости, затем вмешайте петрушку перед подачей в мисках или выдолбленных хрустящих булочках.',
'es': 'Enjuague las almejas en varios cambios de agua fria y escurra bien. Ponga las almejas en una olla grande con 500ml de agua. Cubra, lleve a ebullicion y cocine 2 minutos hasta que se abran. Vierta el contenido de la olla en un colador sobre un tazon para atrapar el caldo de almejas. Cuando esten lo suficientemente frias, retire las almejas de sus conchas - guarde un punado de conchas vacias para presentacion si lo desea. Cuele el caldo en una jarra, dejando cualquier sedimento en el fondo del tazon. Deberia tener alrededor de 800ml de caldo.\nCaliente la mantequilla en la misma olla y fria el tocino por 3-4 minutos hasta que empiece a dorarse. Incorpore la cebolla, el tomillo y el laurel y cocine suavemente por 10 minutos hasta que la cebolla este suave y dorada. Espolvoree la harina y revuelva para formar una pasta, cocine 2 minutos mas, luego gradualmente incorpore el caldo, la leche y la crema.\nAgregue las papas, lleve a fuego lento y deje hervir suavemente por 10 minutos o hasta que las papas esten cocidas. Use un tenedor para aplastar algunos trozos de papa contra el lado de la olla para espesar - pero aun quiere muchos trozos definidos. Incorpore la carne de almeja y las pocas conchas, si lo eligio asi, y cocine a fuego lento un minuto para recalentar. Sazone con bastante pimienta negra y un poco de sal si es necesario, luego incorpore el perejil justo antes de servir en tazones o panes crujientes ahuecados.',
}

# 53154: Clam, chorizo & white bean stew
translations_p6['53154'] = {
'ro': 'Pasul 1\nPrajeste chorizo intr-o tigaie mare cu capac, la foc mediu, pana incepe sa devina crocant si sa elibereze ulei. Adauga ceapa si gateste 5 minute pana incepe sa se inmoaie. Apoi adauga usturoiul si patrunjelul tocat marunt si prajeste inca 1 minut.\n\nPasul 2\nToarna supa si rosiile. Adu la fierbere, reduce focul, apoi adauga fasolea si otetul de sherry. Fierbe la foc mic 10 minute pana lichidul s-a redus putin.\n\nPasul 3\nImprastie scoicile, acopera cu capac si abure 2-4 minute, scuturand tigaia din cand in cand pana se deschid scoicile. Gusteaza inainte de a condimenta, deoarece scoicile pot fi destul de sarate. Apoi presara patrunjelul tocat. Mananca cu multa paine crocanta.',
'ru': 'Шаг 1\nОбжарьте чоризо в большой сковороде с крышкой на среднем огне, пока не начнёт хрустеть и выделять масло. Добавьте лук и готовьте 5 минут до начала размягчения. Затем добавьте чеснок и мелко нарубленную петрушку и жарьте ещё 1 минуту.\n\nШаг 2\nВлейте бульон и помидоры. Доведите до кипения, уменьшите огонь, затем добавьте фасоль и хересный уксус. Тушите 10 минут до небольшого уваривания жидкости.\n\nШаг 3\nРазложите моллюсков, накройте крышкой и парьте 2-4 минуты, периодически встряхивая сковороду, пока моллюски не откроются. Попробуйте перед приправлением, так как моллюски могут быть довольно солёными. Затем посыпьте рубленой петрушкой. Подавайте с хрустящим хлебом.',
'es': 'Paso 1\nFria el chorizo en una sarten grande con tapa a fuego medio hasta que empiece a ponerse crujiente y suelte su aceite. Agregue la cebolla y cocine 5 minutos hasta que empiece a ablandarse. Luego agregue el ajo y el perejil finamente picado y fria 1 minuto mas.\n\nPaso 2\nVierta el caldo y los tomates. Lleve a ebullicion, reduzca el fuego, luego agregue los frijoles y el vinagre de jerez. Cocine a fuego lento 10 minutos hasta que el liquido se reduzca ligeramente.\n\nPaso 3\nEsparza las almejas, cubra con la tapa y cocine al vapor 2-4 minutos, agitando la sarten de vez en cuando hasta que las almejas se abran. Pruebe antes de sazonar, ya que las almejas pueden ser bastante saladas. Luego esparza el perejil picado. Acompane con mucho pan crujiente.',
}

# 52988: Classic Christmas pudding - keep long, just key translations
translations_p6['52988'] = {
'ro': 'Pregateste totul pentru budinca. Toaca migdalele grosier. Curata, scoate cotorul si toaca merele. Ascute cutitul si toaca cojile confiate. (Poti toca migdalele si merele la robotul de bucatarie, dar cojile trebuie facute de mana.) Rade trei sferturi din nucsoara (pare mult dar e corect).\n\nAmesteca migdalele, merele, cojile confiate, nucsoara, stafidele, faina, pesmetul, zaharul muscovado deschis, ouale si 2 linguri de coniac intr-un bol mare.\n\nTinand untul in ambalaj, rade un sfert in bol, apoi amesteca totul. Repeta pana tot untul e ras, apoi amesteca 3-4 minute - amestecul e gata cand se lasa usor dupa fiecare amestecare. Invita familia sa amestece si fiecare sa-si exprime o dorinta.\n\nUnge generos doua boluri de 1,2 litri cu unt si pune un cerc de hartie de copt in fundul fiecaruia. Impacheteaza amestecul de budinca. Acopera cu un strat dublu de hartie de copt, plisand pentru a permite expansiunea, apoi leaga cu sfoara. Taie orice hartie in exces.\n\nAseaza fiecare bol pe o foaie mare de folie si ridica marginile peste, apoi pune alta foaie de folie deasupra si trage-o dedesubt pentru un pachet dublu (face budincile etanse). Leaga cu mai multa sfoara si fa un maner pentru ridicare usoara.\n\nFierbe sau abureste budincile la cuptor 8 ore, adaugand apa dupa nevoie. Scoate din oale si lasa sa se raceasca peste noapte. Cand sunt reci, scoate invelitorile vechi si reinveleste in hartie de copt, folie si sfoara noi. Pastreaza intr-un loc racoros si uscat pana la Craciun.\n\nPentru untul de coniac, bate untul cu coaja de portocala si zaharul pudra. Adauga treptat coniacul si ghimbirul tocat. Pune intr-un bol mic, modeleaza deasupra cu o furculita si pune la frigider sa se intareasca. Untul se pastreaza o saptamana la frigider sau se congeleaza pana la sase saptamani.\n\nDe Craciun, fierbe sau abureste 1 ora. Despacheteaza si rastoarna. Pentru a inflacara, incalzeste 3-4 linguri de coniac intr-o cratita mica, toarna peste budinca si aprinde.',
'ru': 'Подготовьте всё для пудинга. Крупно нарубите миндаль. Очистите, удалите сердцевину и нарубите яблоки. Наточите нож и нарубите цукаты. (Миндаль и яблоки можно порубить в комбайне, но цукаты - только вручную.) Натрите три четверти мускатного ореха (кажется много, но это правильно).\n\nСмешайте миндаль, яблоки, цукаты, мускатный орех, изюм, муку, сухари, светлый сахар мусковадо, яйца и 2 столовые ложки бренди в большой миске.\n\nДержа масло в обёртке, натрите четверть в миску, затем всё перемешайте. Повторяйте, пока всё масло не будет натёрто, затем мешайте 3-4 минуты - смесь готова, когда она слегка оседает после каждого помешивания. Попросите семью тоже помешать и пусть каждый загадает желание.\n\nЩедро смажьте маслом две миски по 1,2 литра и положите кружок пергамента на дно каждой. Утрамбуйте смесь для пудинга. Накройте двойным слоем пергамента, заложив складку для расширения, затем завяжите бечёвкой. Обрежьте лишнюю бумагу.\n\nПоставьте каждую миску на большой лист фольги и поднимите края вверх, затем положите сверху ещё один лист фольги и оберните снизу для двойной упаковки (это делает пудинги водонепроницаемыми). Завяжите ещё бечёвкой и сделайте ручку для удобного извлечения.\n\nВарите или парьте пудинги 8 часов, доливая воду по мере необходимости. Достаньте и остудите на ночь. Когда остынут, снимите старую обёртку и заново заверните в свежий пергамент, фольгу и бечёвку. Храните в прохладном сухом месте до Рождества.\n\nДля масла с бренди взбейте масло с апельсиновой цедрой и сахарной пудрой. Постепенно вбейте бренди и рубленый засахаренный имбирь. Положите в маленькую миску, красиво оформите вилкой и уберите в холодильник для застывания. Масло хранится неделю в холодильнике или замораживается до шести недель.\n\nНа Рождество варите или парьте 1 час. Разверните и переверните. Для фламбирования нагрейте 3-4 столовые ложки бренди в маленькой кастрюле, полейте пудинг и подожгите.',
'es': 'Prepare todo para el pudin. Pique las almendras groseramente. Pele, descorazone y pique las manzanas. Afile su cuchillo y pique las cascaras confitadas. (Puede picar las almendras y manzanas en un procesador, pero las cascaras deben hacerse a mano.) Ralle tres cuartos de la nuez moscada (parece mucho pero es correcto).\n\nMezcle las almendras, manzanas, cascaras confitadas, nuez moscada, pasas, harina, pan rallado, azucar muscovado claro, huevos y 2 cucharadas de brandy en un tazon grande.\n\nSosteniendo la mantequilla en su envoltorio, ralle un cuarto en el tazon, luego revuelva todo. Repita hasta que toda la mantequilla este rallada, luego revuelva por 3-4 minutos - la mezcla esta lista cuando baja ligeramente despues de cada revuelta. Invite a la familia a revolver tambien y que todos pidan un deseo.\n\nEngrase generosamente dos tazones de 1,2 litros y ponga un circulo de papel pergamino en el fondo de cada uno. Empaque la mezcla del pudin. Cubra con una doble capa de papel pergamino, plegandolo para permitir expansion, luego ate con cordel. Recorte el exceso de papel.\n\nColoque cada tazon sobre una hoja grande de papel aluminio y suba los bordes, luego ponga otra hoja encima y bajela por debajo para un paquete doble (esto hace los pudines impermeables). Ate con mas cordel y haga un asa para facilitar sacar y meter de la olla.\n\nHierva o cocine al vapor los pudines por 8 horas, agregando agua segun sea necesario. Retire y deje enfriar toda la noche. Cuando esten frios, retire las envolturas viejas y envuelva de nuevo en papel pergamino, aluminio y cordel frescos. Guarde en un lugar fresco y seco hasta Navidad.\n\nPara la mantequilla de brandy, bata la mantequilla con la ralladura de naranja y el azucar glass. Gradualmente incorpore el brandy y el jengibre confitado picado. Ponga en un tazon pequeno, decore la parte superior con un tenedor y refrigere para que cuaje. La mantequilla se conserva una semana en el refrigerador o se congela hasta seis semanas.\n\nEl dia de Navidad, hierva o cocine al vapor por 1 hora. Desenvuelva y voltee. Para flamear, caliente 3-4 cucharadas de brandy en una olla pequena, vierta sobre el pudin y encienda.',
}

# 53343: Classic Tourtiere
translations_p6['53343'] = {
'ro': 'Incinge uleiul la foc mare intr-o tigaie mare, apoi caleste ceapa si usturoiul pana se inmoaie, circa 5 minute. Adauga carnea tocata de vita, de porc si condimentele si gateste pana carnea se rumeneste.\nAdauga supa de vita si adu la fierbere apoi reduce focul la mediu-mic. Adauga cartoful ras si amesteca. Gateste pana lichidul este aproape absorbit, circa 15 minute. Scoate frunzele de dafin si adauga sare dupa gust. Scoate de pe foc si lasa amestecul sa se raceasca complet - se coace cel mai bine daca umplutura e racita.\nPreincalzeste cuptorul la 190°C. Pe o suprafata usor infainata, intinde un disc de aluat la mai putin de 6mm grosime si tapeteaza o forma de placinta de 23cm. Umple cu amestecul de tourtiere racit si intinde uniform. Intinde aluatul ramas la aceeasi grosime, taie o gaura in centru (pentru abur) si aseaza deasupra umpluturii. Taie aluatul la 1cm dincolo de marginea formei si prinde marginile aluatului. Unge crusta cu ou batut.\nCoace circa 45 minute sau pana aluatul e auriu-rumen. Lasa sa se raceasca 15 minute inainte de a taia.\nPortii: 8-10 (face 2 placinte de 23cm)',
'ru': 'Нагрейте масло на сильном огне в большой сковороде, затем обжарьте лук и чеснок до мягкости, около 5 минут. Добавьте говяжий фарш, свиной фарш и специи и готовьте до подрумянивания мяса.\nДобавьте говяжий бульон и доведите до кипения, затем убавьте огонь до средне-слабого. Добавьте тёртый картофель и перемешайте. Готовьте, пока жидкость почти не впитается, около 15 минут. Удалите лавровые листья и посолите по вкусу. Снимите с огня и полностью остудите начинку - лучше всего печётся, если начинка охлаждена.\nРазогрейте духовку до 190°C. На слегка присыпанной мукой поверхности раскатайте один диск теста толщиной менее 6mm и выложите в форму для пирога 23cm. Наполните остывшей начинкой и разровняйте. Раскатайте оставшееся тесто до той же толщины, вырежьте отверстие в центре (для выхода пара) и поместите поверх начинки. Обрежьте тесто на 1cm за край формы и защипните края. Смажьте корку яичной смесью.\nВыпекайте около 45 минут или до насыщенного золотисто-коричневого цвета теста. Остудите 15 минут перед нарезкой.\nПорции: 8-10 (получается 2 пирога по 23cm)',
'es': 'Caliente el aceite a fuego alto en una sarten grande, luego saltee la cebolla y el ajo hasta que se ablanden, unos 5 minutos. Agregue la carne molida de res, de cerdo y las especias y cocine hasta que la carne se dore.\nAgregue el caldo de res y lleve a fuego lento, luego reduzca el fuego a medio-bajo. Agregue la papa rallada y revuelva. Cocine hasta que el liquido este casi absorbido, unos 15 minutos. Retire las hojas de laurel y agregue sal al gusto. Retire del fuego y deje que la mezcla se enfrie completamente - se hornea mejor si el relleno esta frio.\nPrecaliente el horno a 190°C. En una superficie ligeramente enharinada, estire un disco de masa a menos de 6mm de grosor y forre un molde para pay de 23cm. Rellene con la mezcla fria y distribuya uniformemente. Estire la masa restante al mismo grosor, corte un agujero en el centro (para que escape el vapor) y coloque sobre el relleno. Recorte la masa a 1cm mas alla del borde y pellizque los bordes para sellar. Unte la corteza con huevo batido.\nHornee por unos 45 minutos o hasta que la masa este bien dorada. Deje enfriar 15 minutos antes de rebanar.\nPorciones: 8-10 (rinde 2 pays de 23cm)',
}

# 53037: Coddled pork with cider
translations_p6['53037'] = {
'ro': 'PASUL 1\nIncinge untul intr-o cratita pana sfiraie, apoi prajeste cotletele de porc 2-3 minute pe fiecare parte pana se rumenesc. Scoate din cratita.\n\nPASUL 2\nPune baconul, morcovul, cartofii si napul in cratita, apoi caleste usor pana se coloreaza putin. Adauga varza, aseaza cotletele inapoi deasupra, adauga frunza de dafin, apoi toarna cidrul si supa. Acopera, apoi lasa totul sa fiarba usor 20 minute pana cand porcul e gatit complet si legumele sunt fragede.\n\nPASUL 3\nServeste la masa direct din cratita.',
'ru': 'ШАГ 1\nРастопите масло в кастрюле до шипения, затем обжарьте свиные отбивные 2-3 минуты с каждой стороны до румяности. Достаньте из кастрюли.\n\nШАГ 2\nПоложите бекон, морковь, картофель и брюкву в кастрюлю, затем слегка обжарьте до лёгкого изменения цвета. Добавьте капусту, положите отбивные обратно сверху, добавьте лавровый лист, затем влейте сидр и бульон. Накройте и дайте всему тихо тушиться 20 минут, пока свинина не будет полностью готова, а овощи не станут нежными.\n\nШАГ 3\nПодавайте за столом прямо из кастрюли.',
'es': 'PASO 1\nCaliente la mantequilla en una cacerola hasta que chisporrotee, luego fria las chuletas de cerdo 2-3 minutos de cada lado hasta que se doren. Retire de la cacerola.\n\nPASO 2\nAgrege el tocino, la zanahoria, las papas y el nabo a la cacerola, luego sofria suavemente hasta que se coloreen ligeramente. Incorpore el repollo, coloque las chuletas de vuelta encima, agregue la hoja de laurel, luego vierta la sidra y el caldo. Cubra y deje cocinar a fuego lento por 20 minutos hasta que el cerdo este bien cocido y las verduras esten tiernas.\n\nPASO 3\nSirva en la mesa directamente de la cacerola.',
}

# 52832: Coq au vin
translations_p6['52832'] = {
'ro': 'Incinge 1 lingura de ulei intr-o cratita mare cu fund gros. Pune baconul si prajeste pana devine crocant. Scoate si scurge pe hartie de bucatarie. Adauga salotele in cratita si prajeste, amestecand sau scuturand des, 5-8 minute pana se rumenesc bine. Scoate si pune deoparte cu baconul.\nUsuca bucatile de pui cu hartie de bucatarie. Toarna restul de ulei in cratita si prajeste jumatate din bucatile de pui, intorcand regulat, 5-8 minute pana se rumenesc bine. Scoate si repeta cu restul. Scoate si pune deoparte.\nAdauga usturoiul si prajeste scurt, apoi, cu focul mediu-mare, toarna coniacul, amestecand fundul cratisei pentru a deglasa. Alcoolul trebuie sa sfiraie si sa inceapa sa se evapore.\nPune inapoi pulpele si copanele de pui in cratita impreuna cu sucurile, apoi toarna putin vin, amestecand din nou fundul. Adauga restul de vin, supa si piureul de rosii, pune buchetul garni, condimenteaza cu piper si un varf de sare, apoi intoarce baconul si salotele in cratita. Acopera, reduce focul la foc mic, adauga pieptul de pui si gateste 50 minute-1 ora.\nChiar inainte de servire, incinge uleiul pentru ciuperci intr-o tigaie mare antiaderenta. Adauga ciupercile si prajeste la foc mare cateva minute pana se auriesc. Scoate si tine cald.\nRidica puiul, salotele si baconul din cratita si muta intr-un vas de servire incalzit. Scoate buchetul garni. Pentru ingrosat, amesteca faina, uleiul de masline si untul intr-un bol mic. Adu amestecul de vin la fierbere usoara, apoi adauga treptat bucatele mici de agent de ingrosare, batand cu un tel. Fierbe 1-2 minute. Imprastie ciupercile peste pui, apoi toarna sosul de vin. Garnieste cu patrunjel tocat.',
'ru': 'Нагрейте 1 столовую ложку масла в большой кастрюле с толстым дном. Положите бекон и жарьте до хрустящей корочки. Достаньте и выложите на бумажное полотенце. Добавьте шалот и обжарьте, часто помешивая, 5-8 минут до хорошей румяности. Достаньте и отложите с беконом.\nОбсушите кусочки курицы бумажным полотенцем. Влейте оставшееся масло и обжарьте половину курицы, регулярно переворачивая, 5-8 минут до хорошей румяности. Достаньте и повторите с оставшейся курицей. Достаньте и отложите.\nДобавьте чеснок и кратко обжарьте, затем на средне-сильном огне влейте бренди, соскребая дно кастрюли для деглазирования. Алкоголь должен зашипеть и начать испаряться.\nВерните куриные ножки и бёдра в кастрюлю вместе с соками, затем влейте немного вина, снова соскребая дно. Добавьте остальное вино, бульон и томатное пюре, опустите букет гарни, приправьте перцем и щепоткой соли, затем верните бекон и шалот. Накройте, убавьте огонь, добавьте куриные грудки и готовьте 50 минут-1 час.\nПеред подачей нагрейте масло для грибов в большой антипригарной сковороде. Добавьте грибы и обжарьте на сильном огне несколько минут до золотистого цвета. Достаньте и держите тёплыми.\nДостаньте курицу, шалот и бекон из кастрюли и переложите в тёплое сервировочное блюдо. Удалите букет гарни. Для загустителя смешайте муку, оливковое масло и масло в маленькой миске. Доведите винную смесь до лёгкого кипения, затем постепенно добавляйте маленькие кусочки загустителя, взбивая венчиком. Тушите 1-2 минуты. Разложите грибы поверх курицы и полейте винным соусом. Украсьте рубленой петрушкой.',
'es': 'Caliente 1 cucharada de aceite en una cacerola grande de fondo grueso. Agregue el tocino y fria hasta que este crujiente. Retire y escurra sobre papel de cocina. Agregue los chalotes y fria, revolviendo a menudo, por 5-8 minutos hasta que esten bien dorados. Retire y reserve con el tocino.\nSeque las piezas de pollo con papel de cocina. Vierta el aceite restante y fria la mitad de las piezas, volteando regularmente, por 5-8 minutos hasta que esten bien doradas. Retire y repita con el resto. Retire y reserve.\nAgregue el ajo y fria brevemente, luego a fuego medio-alto vierta el brandy, raspando el fondo de la cacerola para deglasear. El alcohol debe chisporrotear y empezar a evaporarse.\nRegrese las piernas y muslos de pollo a la cacerola con sus jugos, luego vierta un poco de vino, raspando el fondo nuevamente. Incorpore el resto del vino, el caldo y el pure de tomate, agregue el bouquet garni, sazone con pimienta y una pizca de sal, luego regrese el tocino y los chalotes. Cubra, baje el fuego, agregue las pechugas y cocine 50 minutos-1 hora.\nJusto antes de servir, caliente el aceite para los hongos en una sarten grande antiadherente. Agregue los hongos y fria a fuego alto unos minutos hasta que esten dorados. Retire y mantenga tibios.\nSaque el pollo, los chalotes y el tocino y pase a un platon tibio. Retire el bouquet garni. Para el espesante, mezcle la harina, el aceite de oliva y la mantequilla en un tazon pequeno. Lleve la mezcla de vino a un hervor suave, luego gradualmente agregue pedacitos del espesante, batiendo con un batidor. Cocine a fuego lento 1-2 minutos. Esparza los hongos sobre el pollo y vierta la salsa de vino. Decore con perejil picado.',
}

# Name fixes dict: recipe_id -> { 'ro': ..., 'ru': ..., 'es': ... }
name_fixes = {
    '52990': {'ro': 'Tort de Craciun', 'ru': 'Рождественский торт', 'es': 'Pastel de Navidad'},
    '52788': {'ro': 'Batoane de ovaz cu budinca de Craciun', 'ru': 'Флэпджек с рождественским пудингом', 'es': 'Barritas de avena con pudin de Navidad'},
    '52989': {'ro': 'Trifle cu budinca de Craciun', 'ru': 'Трайфл с рождественским пудингом', 'es': 'Trifle con pudin de Navidad'},
    '53283': {'ro': 'Chtitha Batata (tocana algeriana de cartofi)', 'ru': 'Штиса Батата (алжирское рагу из картофеля)', 'es': 'Chtitha Batata (estofado argelino de papa)'},
    '53153': {'ro': 'Churros', 'ru': 'Чуррос', 'es': 'Churros'},
    '53116': {'ro': 'Chiflute cu scortisoara', 'ru': 'Булочки с корицей', 'es': 'Bollitos de canela'},
    '52840': {'ro': 'Supa de scoici', 'ru': 'Похлёбка из моллюсков', 'es': 'Sopa de almejas'},
    '53154': {'ro': 'Tocana de scoici, chorizo si fasole alba', 'ru': 'Рагу с моллюсками, чоризо и белой фасолью', 'es': 'Estofado de almejas, chorizo y frijoles blancos'},
    '52988': {'ro': 'Budinca clasica de Craciun', 'ru': 'Классический рождественский пудинг', 'es': 'Pudin clasico de Navidad'},
    '53343': {'ro': 'Tourtiere clasica', 'ru': 'Классический туртьер', 'es': 'Tourtiere clasica'},
    '53037': {'ro': 'Porc fiert la abur cu cidru', 'ru': 'Тушёная свинина с сидром', 'es': 'Cerdo estofado con sidra'},
    '53185': {'ro': 'Salata de chorizo si rosii', 'ru': 'Салат с чоризо и помидорами', 'es': 'Ensalada de chorizo y tomate'},
    '53159': {'ro': 'Omleta cu chorizo, cartofi si branza', 'ru': 'Омлет с чоризо, картофелем и сыром', 'es': 'Omelette de chorizo, papa y queso'},
    '53063': {'ro': 'Chivito uruguayan', 'ru': 'Чивито по-уругвайски', 'es': 'Chivito uruguayo'},
    '52831': {'ro': 'Pui Karaage', 'ru': 'Курица караагэ', 'es': 'Pollo Karaage'},
    '52920': {'ro': 'Pui Marengo', 'ru': 'Курица Маренго', 'es': 'Pollo Marengo'},
    '52795': {'ro': 'Pui Handi', 'ru': 'Курица Ханди', 'es': 'Pollo Handi'},
    '52879': {'ro': 'Pui Parmentier', 'ru': 'Курица Парментье', 'es': 'Pollo Parmentier'},
}

print("Phase 6 translations and name fixes defined")
