#!/usr/bin/env python3
"""Part 2: More recipe translations"""

translations_p2 = {}

# 52920: Chicken Marengo
translations_p2['52920'] = {
'ro': 'Incinge uleiul intr-o cratita mare rezistenta la foc si caleste ciupercile pana incep sa se inmoaie. Adauga pulpele de pui si rumeneste scurt pe fiecare parte.\nToarna passata, sfarama cubul de supa si adauga maslinele. Condimenteaza cu piper negru - nu ar trebui sa ai nevoie de sare. Acopera si fierbe la foc mic 40 minute pana cand puiul este fraged. Presara cu patrunjel si serveste cu paste si salata, sau piure si legume verzi, dupa preferinta.',
'ru': 'Разогрейте масло в большой жаропрочной кастрюле и обжарьте грибы до мягкости. Добавьте куриные ножки и слегка подрумяньте с каждой стороны.\nВлейте пассату, раскрошите бульонный кубик и добавьте оливки. Приправьте чёрным перцем - соль не должна понадобиться. Накройте и тушите 40 минут до мягкости курицы. Посыпьте петрушкой и подавайте с пастой и салатом, или пюре и зелёными овощами по желанию.',
'es': 'Caliente el aceite en una cacerola grande resistente al fuego y saltee los hongos hasta que empiecen a ablandarse. Agregue las piernas de pollo y dore brevemente de cada lado.\nVierta la passata, desmenuce el cubito de caldo e incorpore las aceitunas. Sazone con pimienta negra - no deberia necesitar sal. Cubra y cocine a fuego lento por 40 minutos hasta que el pollo este tierno. Espolvoree con perejil y sirva con pasta y ensalada, o pure y verduras, si lo desea.',
}

# 52879: Chicken Parmentier
translations_p2['52879'] = {
'ro': 'Pentru topping, fierbe cartofii in apa cu sare pana se inmoaie. Scurge-i si trece-i printr-un strecurator de cartofi, sau zdrobeste-i bine. Amesteca untul, smantana si galbenusurile. Condimenteaza si pune deoparte.\nPentru umplutura, topeste untul intr-o tigaie mare. Adauga salotele, morcovii si telina si caleste usor pana se inmoaie, apoi adauga usturoiul. Toarna vinul si gateste 1 minut. Amesteca piureul de rosii, rosiile tocate si supa si gateste 10-15 minute, pana se ingroasa. Adauga puiul sfasiat, maslinele si patrunjelul. Condimenteaza dupa gust cu sare si piper.\nPreincalzeste cuptorul la 180C/160C ventilator/gaz 4.\nPune umplutura intr-o tava de 20x30cm rezistenta la cuptor si acopera cu piureul de cartofi. Rade branza Gruyere deasupra. Coace 30-35 minute, pana este foarte fierbinte si cartofii sunt auriu-rumeni.',
'ru': 'Для верхнего слоя сварите картофель в подсоленной воде до мягкости. Слейте и пропустите через картофелемялку или тщательно разомните. Вмешайте масло, сливки и яичные желтки. Приправьте и отставьте.\nДля начинки растопите масло в большой сковороде. Добавьте шалот, морковь и сельдерей и обжарьте до мягкости, затем добавьте чеснок. Влейте вино и готовьте 1 минуту. Вмешайте томатное пюре, нарезанные помидоры и бульон и готовьте 10-15 минут до загустения. Добавьте измельчённую курицу, оливки и петрушку. Приправьте по вкусу солью и перцем.\nРазогрейте духовку до 180C/160C вентилятор/газ 4.\nВыложите начинку в форму 20x30cm для запекания и покройте картофельным пюре. Натрите сверху грюйер. Запекайте 30-35 минут, пока не станет очень горячим, а картофель не подрумянится.',
'es': 'Para la cobertura, hierva las papas en agua con sal hasta que esten tiernas. Escurra y pase por un prensapapas, o aplaste bien. Incorpore la mantequilla, la crema y las yemas de huevo. Sazone y reserve.\nPara el relleno, derrita la mantequilla en una sarten grande. Agregue los chalotes, las zanahorias y el apio y sofria hasta que se ablanden, luego agregue el ajo. Vierta el vino y cocine 1 minuto. Incorpore el pure de tomate, los tomates picados y el caldo y cocine 10-15 minutos hasta que espese. Agregue el pollo desmenuzado, las aceitunas y el perejil. Sazone al gusto con sal y pimienta.\nPrecaliente el horno a 180C/160C ventilador/gas 4.\nColoque el relleno en un molde refractario de 20x30cm y cubra con el pure de papa. Ralle el queso gruyere encima. Hornee 30-35 minutos, hasta que este bien caliente y la papa este dorada.',
}

# 53011: Chicken Quinoa Greek Salad
translations_p2['53011'] = {
'ro': 'Gateste quinoa conform instructiunilor de pe ambalaj, apoi clateste in apa rece si scurge bine.\n\nIntre timp, amesteca untul, ardeiul iute si usturoiul intr-o pasta. Amesteca fileurile de pui in 2 lingurite de ulei de masline cu condimente. Aseaza-le intr-o tigaie gratar fierbinte si gateste 3-4 minute pe fiecare parte sau pana sunt gatite complet. Muta pe o farfurie, pune untul picant deasupra si lasa-l sa se topeasca.\n\nAdauga rosiile, maslinele, ceapa, feta si menta intr-un bol. Amesteca quinoa gatita. Incorporeaza restul de ulei de masline, sucul si coaja de lamaie si condimenteaza bine. Serveste cu fileurile de pui deasupra, stropite cu sucul de pui cu unt.',
'ru': 'Приготовьте киноа согласно инструкции на упаковке, затем промойте холодной водой и хорошо слейте.\n\nТем временем смешайте масло, чили и чеснок в пасту. Обваляйте куриные филе в 2 чайных ложках оливкового масла с приправами. Положите на горячую сковороду-гриль и готовьте 3-4 минуты с каждой стороны или до полной готовности. Переложите на тарелку, положите сверху пряное масло и дайте ему растаять.\n\nПоложите помидоры, оливки, лук, фету и мяту в миску. Добавьте приготовленную киноа. Вмешайте оставшееся оливковое масло, лимонный сок и цедру, хорошо приправьте. Подавайте с куриными филе сверху, полив оставшимся маслянистым куриным соком.',
'es': 'Cocine la quinoa siguiendo las instrucciones del paquete, luego enjuague con agua fria y escurra bien.\n\nMientras tanto, mezcle la mantequilla, el chile y el ajo en una pasta. Cubra los filetes de pollo con 2 cucharaditas de aceite de oliva y sazonador. Coloquelos en una sarten parrilla caliente y cocine 3-4 minutos de cada lado o hasta que esten bien cocidos. Pase a un plato, ponga la mantequilla picante encima y deje que se derrita.\n\nColoque los tomates, las aceitunas, la cebolla, el queso feta y la menta en un tazon. Agregue la quinoa cocida. Incorpore el aceite de oliva restante, el jugo y la ralladura de limon y sazone bien. Sirva con los filetes de pollo encima, banados con los jugos de pollo con mantequilla.',
}

# 53218: Chicken Shawarma
translations_p2['53218'] = {
'ro': '1\nIncepe prin a taia puiul in felii destul de mici. Ia punga cu fermoar si pune puiul feliat proaspat inauntru.\n2\nAdauga usturoi, coriandru, chimion, cardamom, piper cayenne, boia, sare, piper, suc de lamaie si ulei de masline in punga. Inchide punga si amesteca bine. Pune la frigider 10-12 ore (mai putin e bine dar mai mult e mai bun).\n3\nCand esti gata sa gatesti, incinge tigaia la foc mediu-mare si adauga putin ulei de masline. Prajeste o parte a tuturor lipiilor pana sunt usor rumenite. Scoate din tigaie, adauga suficient ulei sa acopere tigaia. Pune cartofii prajiti crocanti in friteuza cu aer la 180 grade 15 minute, scuturand din cand in cand.\n4\nTigaia ar trebui sa fie destul de fierbinte acum, adauga puiul in 2 serii (daca nu ai o tigaie mare) pentru a evita aglomerarea. Puiul trebuie sa capete o culoare frumoasa rumenita, ceea ce e perfect. Gateste inca 5-8 minute sau pana e gatit complet. Repeta cu urmatoarea serie.\n5\nIn timp ce puiul se gateste, pune iaurtul grecesc intr-un bol. Combina usturoiul, menta si patrunjelul tocat marunt, o stoarcere de lamaie si chimion. Combina si adauga sare dupa gust. Intr-un bol mic, combina 1 lingurita pudra de usturoi, boia, chimion, pudra de ceapa, oregano, patrunjel uscat, piper cayenne (optional), amesteca si pune deoparte pentru cartofi.\n6\nCondimenteaza cartofii imediat ce sunt gatiti si adauga sare dupa gust. Cand puiul este gata, serveste imediat: intinde lipia, intinde sosul uniform pe paine, adauga salata, ceapa, rosie, cartofi, pui, feta si mai mult sos deasupra. Serveste imediat.',
'ru': '1\nНачните с нарезки курицы на достаточно мелкие кусочки. Возьмите пакет с застёжкой и положите нарезанную курицу внутрь.\n2\nДобавьте чеснок, кориандр, тмин, кардамон, кайенский перец, паприку, соль, перец, лимонный сок и оливковое масло в пакет. Закройте пакет и хорошо перемешайте. Уберите в холодильник на 10-12 часов (меньше допустимо, но дольше лучше).\n3\nКогда будете готовы, нагрейте сковороду на средне-сильном огне и добавьте немного оливкового масла. Обжарьте одну сторону всех лепёшек до лёгкой румяности. Снимите со сковороды, добавьте достаточно масла, чтобы покрыть сковороду. Положите картофель фри в аэрогриль при 180 градусах на 15 минут, периодически встряхивая.\n4\nСковорода должна быть достаточно горячей, добавьте курицу в 2 партии (если у вас нет большой сковороды) чтобы избежать перегрузки. Курица должна получить красивую поджарку и тёмный цвет, это идеально. Готовьте ещё 5-8 минут или до полной готовности. Повторите со следующей партией.\n5\nПока курица готовится, положите греческий йогурт в миску. Смешайте чеснок, мелко нарезанные мяту и петрушку, немного лимонного сока и тмин. Перемешайте и посолите по вкусу. В маленькой миске смешайте 1 чайную ложку чесночного порошка, паприку, тмин, луковый порошок, орегано, сушёную петрушку, кайенский перец (по желанию), перемешайте и отставьте для картофеля.\n6\nПриправьте картофель сразу после готовности и посолите по вкусу. Когда курица готова, подавайте немедленно: разложите лепёшку, равномерно намажьте соус на хлеб, добавьте салат, лук, помидор, картофель фри, курицу, фету и ещё соус сверху. Подавайте немедленно.',
'es': '1\nComience cortando el pollo en rebanadas razonablemente pequenas. Tome su bolsa con cierre y ponga el pollo recien rebanado dentro.\n2\nAgregue ajo, cilantro, comino, cardamomo, pimienta de cayena, pimenton, sal, pimienta, jugo de limon y aceite de oliva a la bolsa. Cierre la bolsa y mezcle bien. Coloque en el refrigerador por 10-12 horas (menos tiempo esta bien pero mas tiempo es mejor).\n3\nCuando este listo para cocinar, caliente la sarten a fuego medio-alto y agregue un poco de aceite de oliva. Fria un lado de todos los panes planos hasta que esten ligeramente tostados. Retire de la sarten, agregue suficiente aceite para cubrir la sarten. Ponga las papas fritas en la freidora de aire a 180 grados por 15 minutos, agitando de vez en cuando.\n4\nLa sarten deberia estar bastante caliente a este punto, agregue el pollo en 2 tandas (a menos que tenga una sarten grande) para evitar saturarla. El pollo debe obtener un buen sello y color oscuro, lo cual es perfecto. Cocine otros 5-8 minutos o hasta que este bien cocido. Repita con la siguiente tanda.\n5\nMientras el pollo se cocina, ponga el yogur griego en un tazon. Combine el ajo, la menta y el perejil finamente picados, un chorrito de limon y comino. Combine y agregue sal al gusto. En un tazon pequeno, combine 1 cucharadita de ajo en polvo, pimenton, comino, cebolla en polvo, oregano, perejil seco, pimienta de cayena (opcional), mezcle y reserve para las papas fritas.\n6\nSazone las papas fritas inmediatamente al sacarlas y agregue sal al gusto. Una vez que el pollo este listo, sirva inmediatamente: extienda el pan plano, unte la salsa uniformemente sobre el pan, agregue lechuga, cebolla, tomate, papas fritas, pollo, queso feta y mas salsa encima. Sirva inmediatamente.',
}

# 53261: Chicken wings with cumin, lemon & garlic
translations_p2['53261'] = {
'ro': 'Pasul 1\nFolosind o foarfeca ascutita de bucatarie, taie fiecare aripa la articulatie in doua bucati. Amesteca usturoiul, coaja si sucul de lamaie, chimionul si uleiul cu condimente din abundenta, apoi pune intr-un vas cu aripioarele de pui si amesteca pentru a le acoperi. Acopera si pune la frigider sa se marineze cel putin 1 ora, sau peste noapte daca ai timp.\n\nPasul 2\nIncinge cuptorul la 200C/180C ventilator/gaz 6, sau incinge un gratar exterior. Coace aripioarele pe o tava de cuptor 45-50 minute pana sunt crocante, sau la gratar 20 minute, stropind cu miere in ultimele 10 minute ale fiecarei metode. Serveste pe o farfurie mare cu multe servetele de hartie. Umple boluri mici cu masline, fistic sau migdale, curmale si ardei iuti murati si lipii pentru a servi alaturi, impreuna cu garniturile de mai jos.',
'ru': 'Шаг 1\nОстрыми кухонными ножницами разрежьте каждое крылышко на две части по суставу. Смешайте чеснок, цедру и сок лимона, тмин и масло с обильными приправами, затем переложите в блюдо с куриными крылышками и перемешайте для покрытия. Накройте и уберите в холодильник мариноваться минимум на 1 час, или на ночь если есть время.\n\nШаг 2\nРазогрейте духовку до 200C/180C вентилятор/газ 6, или разожгите уличный гриль. Запекайте крылышки на противне 45-50 минут до хрустящей корочки, или на гриле 20 минут, поливая мёдом в последние 10 минут каждого способа. Подавайте на большом блюде с большим количеством бумажных салфеток. Наполните маленькие миски оливками, фисташками или миндалём, финиками и маринованным чили, и лепёшками для подачи рядом.',
'es': 'Paso 1\nUsando unas tijeras de cocina afiladas, corte cada ala en la articulacion en dos piezas. Mezcle el ajo, la ralladura y jugo de limon, el comino y el aceite con abundante sazonador, luego vierta en un plato con las alitas de pollo y revuelva para cubrirlas. Cubra y ponga en el refrigerador a marinar por al menos 1 hora, o toda la noche si tiene tiempo.\n\nPaso 2\nCaliente el horno a 200C/180C ventilador/gas 6, o caliente una parrilla al aire libre. Hornee las alitas en una bandeja por 45-50 minutos hasta que esten crujientes, o ase en la parrilla por 20 minutos, rociando con miel en los ultimos 10 minutos de cada metodo. Sirva en una fuente grande con muchas servilletas de papel. Llene tazones pequenos con aceitunas, pistachos o almendras, datiles y chiles encurtidos y panes planos para servir al lado.',
}

# 53186: Chicken with saffron, raisins & pine nuts
translations_p2['53186'] = {
'ro': 'Pasul 1\nIncinge o tigaie mare pe foc mare si condimenteaza puiul. Adauga uleiul de masline in tigaie, apoi puiul. Rumeneste circa 5 minute pe fiecare parte, scoate pe o farfurie si pune deoparte.\n\nPasul 2\nReduce focul la mediu. In grasimea ramasa, prajeste ceapa 3 minute, apoi adauga usturoiul si sofranul. Gateste inca 3-4 minute. Adauga sherry-ul si fierbe la foc mic 3-5 minute pana devine siropos.\n\nPasul 3\nPune bucatile de pulpa de pui inapoi in tigaie, adauga supa, cimbrul si stafidele, acopera si gateste la foc mic 20 minute. Adauga pieptul de pui si orice suc ramas pe farfurie. Fierbe la foc mic inca 10 minute pana se gateste complet si sosul din tigaie s-a redus.\n\nPasul 4\nIn timp ce puiul se gateste, incinge cuptorul la 200C/180C ventilator/gaz 6. Imprastie muguri de pin pe o tava si prajeste-i 10 minute pana se auriesc. Cand puiul s-a gatit, condimenteaza dupa gust, presara muguri de pin si patrunjel, apoi serveste cu orez.',
'ru': 'Шаг 1\nРазогрейте большую сковороду на сильном огне и приправьте курицу. Добавьте оливковое масло в сковороду, затем курицу. Обжарьте около 5 минут с каждой стороны, переложите на тарелку и отставьте.\n\nШаг 2\nУменьшите огонь до среднего. В оставшемся жире обжарьте лук 3 минуты, затем добавьте чеснок и шафран. Готовьте ещё 3-4 минуты. Добавьте херес и тушите 3-5 минут до сиропообразного состояния.\n\nШаг 3\nВерните куриные ножки в сковороду, добавьте бульон, тимьян и изюм, накройте и готовьте на слабом огне 20 минут. Добавьте грудку и оставшийся сок с тарелки. Тушите ещё 10 минут до полной готовности и уваривания соуса.\n\nШаг 4\nПока курица готовится, разогрейте духовку до 200C/180C вентилятор/газ 6. Рассыпьте кедровые орехи на противне и поджарьте 10 минут до золотистого цвета. Когда курица готова, приправьте по вкусу, посыпьте кедровыми орехами и петрушкой, подавайте с рисом.',
'es': 'Paso 1\nCaliente una sarten grande a fuego alto y sazone el pollo. Agregue el aceite de oliva a la sarten, luego el pollo. Dore por unos 5 minutos de cada lado, retire a un plato y reserve.\n\nPaso 2\nBaje el fuego a medio. En la grasa restante, fria la cebolla por 3 minutos, luego agregue el ajo y el azafran. Cocine 3-4 minutos mas. Agregue el jerez y cocine a fuego lento 3-5 minutos hasta que este almibarado.\n\nPaso 3\nRegrese las piezas de muslo de pollo a la sarten, agregue el caldo, el tomillo y las pasas, cubra y cocine a fuego lento por 20 minutos. Agregue la pechuga y los jugos que queden en el plato. Cocine a fuego lento 10 minutos mas hasta que este completamente cocido y la salsa se haya reducido.\n\nPaso 4\nMientras el pollo se cocina, caliente el horno a 200C/180C ventilador/gas 6. Esparza los pinones en una bandeja y tueste por 10 minutos hasta que esten dorados. Cuando el pollo este cocido, sazone al gusto, esparza pinones y perejil, y sirva con arroz.',
}

# 52870: Chickpea Fajitas
translations_p2['52870'] = {
'ro': 'Incinge cuptorul la 200C/180C ventilator/gaz 6 si tapeteaza o tava cu folie. Scurge naut-ul, usuca-l si pune-l pe tava pregatita. Adauga uleiul si boia, amesteca pentru a acoperi, apoi coace 20-25 minute pana se rumeneste si devine crocant, scuturand la jumatatea timpului de gatit.\n\nIntre timp, pune rosiile si ceapa intr-un bol mic cu otetul si pune deoparte sa se mureze. Pune avocado in alt bol si zdrobeste-l cu o furculita, lasand cateva bucati mai mari. Adauga sucul de lamaie verde si condimenteaza bine. Amesteca smantana cu harissa si pune deoparte pana la servire.\n\nIncinge o tigaie gratar pana aproape fumeaza. Adauga tortillas, una cate una, rumenind fiecare parte pana sunt fierbinti cu linii de gratar.\n\nPune totul pe masa si asambleaza fajitas: intinde putin crema de harissa pe tortilla, adauga naut copt, guacamole, salsa murata si coriandru, dupa preferinta. Serveste cu felii de lamaie verde pentru a stoarce deasupra.',
'ru': 'Разогрейте духовку до 200C/180C вентилятор/газ 6 и застелите противень фольгой. Слейте нут, обсушите и высыпьте на подготовленный противень. Добавьте масло и паприку, перемешайте для покрытия, затем запекайте 20-25 минут до румяности и хрустящей корочки, встряхивая на половине времени.\n\nТем временем положите помидоры и лук в маленькую миску с уксусом и отставьте мариноваться. Положите авокадо в другую миску и разомните вилкой, оставляя крупные кусочки. Вмешайте сок лайма и хорошо приправьте. Смешайте сметану с хариссой и отставьте до подачи.\n\nРазогрейте сковороду-гриль до почти дымящегося состояния. Кладите тортильи по одной, обжаривая каждую сторону до горячего состояния с полосками от гриля.\n\nВыложите всё на стол и собирайте фахитас: намажьте немного крема с хариссой на тортилью, положите сверху запечённый нут, гуакамоле, маринованную сальсу и кинзу по желанию. Подавайте с дольками лайма для выжимания.',
'es': 'Caliente el horno a 200C/180C ventilador/gas 6 y forre una bandeja con papel aluminio. Escurra los garbanzos, sequelos y coloquelos en la bandeja preparada. Agregue el aceite y el pimenton, revuelva para cubrir, luego ase por 20-25 minutos hasta que esten dorados y crujientes, agitando a la mitad de la coccion.\n\nMientras tanto, ponga los tomates y la cebolla en un tazon pequeno con el vinagre y reserve para encurtir. Ponga el aguacate en otro tazon y aplaste con un tenedor, dejando algunos trozos grandes. Incorpore el jugo de lima y sazone bien. Mezcle la crema agria con la harissa y reserve hasta servir.\n\nCaliente una sarten parrilla hasta que casi eche humo. Agregue las tortillas, una a la vez, tostando cada lado hasta que esten calientes con marcas de parrilla.\n\nPonga todo en la mesa y arme las fajitas: unte un poco de crema de harissa sobre la tortilla, cubra con garbanzos asados, guacamole, salsa encurtida y cilantro, si lo desea. Sirva con rodajas de lima para exprimir encima.',
}

# 53166: Chickpea, chorizo & spinach stew
translations_p2['53166'] = {
'ro': 'Pasul 1\nIncinge uleiul intr-o tigaie mare, apoi caleste ceapa 3-4 minute pana incepe sa se inmoaie. Adauga morcovul, telina, cimbrul si frunzele de dafin. Condimenteaza, apoi gateste 2-3 minute, amestecand din cand in cand. Adauga usturoiul, chorizo, scortisoara si boia afumata. Caleste pana cand legumele se inmoaie si chorizo incepe sa elibereze ulei si sa devina crocant.\n\nPasul 2\nAdauga naut-ul, otetul si 150ml apa, apoi adu la fierbere 1-2 minute pana cand naut-ul s-a incalzit. Adauga spanacul si amesteca-l prin naut pana se ofileste putin. Scoate de pe foc, condimenteaza dupa gust si serveste cald cu paine crocanta.',
'ru': 'Шаг 1\nНагрейте масло в большой сковороде, затем обжарьте лук 3-4 минуты до начала размягчения. Добавьте морковь, сельдерей, тимьян и лавровые листья. Приправьте, затем готовьте 2-3 минуты, периодически помешивая. Добавьте чеснок, чоризо, корицу и копчёную паприку. Обжаривайте, пока овощи не размягчатся, а чоризо не начнёт выделять масло и становиться хрустящим.\n\nШаг 2\nДобавьте нут, уксус и 150ml воды, доведите до кипения на 1-2 минуты, пока нут не прогреется. Добавьте шпинат и перемешайте с нутом, пока он слегка не увянет. Снимите с огня, приправьте по вкусу и подавайте тёплым с хрустящим хлебом.',
'es': 'Paso 1\nCaliente el aceite en una sarten grande, luego sofria la cebolla por 3-4 minutos hasta que empiece a ablandarse. Incorpore la zanahoria, el apio, el tomillo y las hojas de laurel. Sazone, luego cocine 2-3 minutos, revolviendo de vez en cuando. Agregue el ajo, el chorizo, la canela y el pimenton ahumado. Sofria hasta que las verduras se ablanden y el chorizo empiece a soltar sus aceites y se ponga crujiente.\n\nPaso 2\nIncorpore los garbanzos, el vinagre y 150ml de agua, luego lleve a fuego lento por 1-2 minutos hasta que los garbanzos se hayan calentado. Agregue la espinaca y revuelva con los garbanzos hasta que se marchite un poco. Retire del fuego, sazone al gusto y sirva tibio con pan crujiente.',
}

# 53265: Chilli ginger lamb chops
translations_p2['53265'] = {
'ro': 'Pasul 1\nPune usturoiul intr-un bol cu ghimbirul, sucul de lamaie, uleiul, condimentele si sare si piper. Mixeaza cu un blender de mana pana devine neted, apoi foloseste pentru a acoperi cotletele de miel pe ambele parti. Lasa sa se marineze la frigider cateva ore sau peste noapte.\n\nPasul 2\nIncinge gratarul pana este fierbinte. Gateste cotletele pe gratar 3 minute pe fiecare parte pana sunt gatite dar inca roz si suculente in interior.',
'ru': 'Шаг 1\nПоложите чеснок в миску с имбирём, лимонным соком, маслом, специями и приправами. Измельчите погружным блендером до однородности, затем используйте для покрытия бараньих котлет с обеих сторон. Оставьте мариноваться в холодильнике на пару часов или на ночь.\n\nШаг 2\nРазогрейте гриль до горячего состояния. Жарьте котлеты на гриле по 3 минуты с каждой стороны до готовности, но чтобы внутри они оставались розовыми и сочными.',
'es': 'Paso 1\nPonga el ajo en un tazon con el jengibre, el jugo de limon, el aceite, las especias y el sazonador. Licue con una licuadora de mano hasta que quede suave, luego use para cubrir las chuletas de cordero por ambos lados. Deje marinar en el refrigerador por un par de horas o toda la noche.\n\nPaso 2\nCaliente una parrilla hasta que este bien caliente. Ase las chuletas sobre las brasas por 3 minutos de cada lado hasta que esten cocidas pero aun rosadas y jugosas en el centro.',
}

# 52839: Chilli prawn linguine
translations_p2['52839'] = {
'ro': 'Amesteca ingredientele pentru dressing intr-un bol mic si condimenteaza cu sare si piper. Pune deoparte.\n\nGateste pastele conform instructiunilor de pe ambalaj. Adauga mazarea dulce in ultimul minut de gatit.\n\nIntre timp, incinge uleiul intr-un wok sau tigaie mare, adauga usturoiul si ardeiul iute si caleste la foc usor circa 30 secunde fara a lasa usturoiul sa se rumeneasca. Adauga crevetii si gateste la foc mare, amestecand des, circa 3 minute pana devin roz.\n\nAdauga rosiile si gateste, amestecand din cand in cand, 3 minute pana incep sa se inmoaie. Scurge pastele si mazarea bine, apoi adauga-le in amestecul cu creveti. Rupe frunzele de busuioc, amesteca si condimenteaza cu sare si piper.\n\nServeste cu frunze de salata stropite cu dressingul de lamaie verde si paine calda crocanta.',
'ru': 'Смешайте ингредиенты для заправки в маленькой миске и приправьте солью и перцем. Отставьте.\n\nСварите пасту согласно инструкции на упаковке. Добавьте сахарный горошек в последнюю минуту варки.\n\nТем временем разогрейте масло в воке или большой сковороде, добавьте чеснок и чили и готовьте на слабом огне около 30 секунд, не давая чесноку подрумяниться. Добавьте креветки и готовьте на сильном огне, часто помешивая, около 3 минут до розового цвета.\n\nДобавьте помидоры и готовьте, периодически помешивая, 3 минуты, пока не начнут размягчаться. Хорошо слейте пасту и горошек, затем добавьте к креветочной смеси. Порвите листья базилика, перемешайте и приправьте солью и перцем.\n\nПодавайте с листьями салата, политыми заправкой с лаймом, и тёплым хрустящим хлебом.',
'es': 'Mezcle los ingredientes del aderezo en un tazon pequeno y sazone con sal y pimienta. Reserve.\n\nCocine la pasta segun las instrucciones del paquete. Agregue los guisantes dulces en el ultimo minuto de coccion.\n\nMientras tanto, caliente el aceite en un wok o sarten grande, agregue el ajo y el chile y cocine a fuego suave unos 30 segundos sin dejar que el ajo se dore. Agregue los langostinos y cocine a fuego alto, revolviendo frecuentemente, unos 3 minutos hasta que se pongan rosados.\n\nAgregue los tomates y cocine, revolviendo de vez en cuando, por 3 minutos hasta que empiecen a ablandarse. Escurra bien la pasta y los guisantes, luego anadalo a la mezcla de langostinos. Desgarre las hojas de albahaca, revuelva y sazone con sal y pimienta.\n\nSirva con hojas de lechuga rociadas con el aderezo de lima y pan crujiente caliente.',
}

print("Phase 2 translations defined")
