#!/usr/bin/env python3
"""Part 4: Remaining recipe translations"""

translations_p4 = {}

# 52856: Choc Chip Pecan Pie
translations_p4['52856'] = {
'ro': 'Mai intai, pregateste aluatul. Pune ingredientele intr-un robot de bucatarie cu 1/4 lingurita de sare. Mixeaza pana amestecul seamana cu pesmetul. Stropeste 2-3 lingurite de apa rece in palnie in timp ce lama se roteste - amestecul ar trebui sa inceapa sa se adune. Pune pe suprafata de lucru si aduna, framantand scurt intr-o bila. Apasa intr-un disc, inveleste in folie alimentara si pune la rece cel putin 20 minute. Incinge cuptorul la 200C/180C ventilator/gaz 6.\n\nScoate aluatul din frigider si lasa la temperatura camerei 5 minute sa se inmoaie. Infaineaza suprafata de lucru, apoi desfasoara aluatul si intinde-l intr-un cerc cu grosimea unei monede. Tapeteaza o forma adanca rotunda canelata de 23cm - a mea avea circa 3cm adancime. Apasa aluatul in colturi si pe margini, asigurandu-te ca nu sunt goluri. Lasa 1cm de aluat in exces (pastreaza niste resturi de aluat pentru mai tarziu). Tapeteaza cu hartie de copt (mototoloeste-o intai pentru a o face mai flexibila) si umple cu fasole de copt. Coace orb 15-20 minute pana marginile sunt intarite, apoi scoate hartia si fasolea si pune inapoi la cuptor 5 minute pana se rumeneste. Taie aluatul la nivelul marginii formei - un cutit mic zimtat e cel mai bun. Daca sunt crapaturi, repara-le cu resturile de aluat.\n\nIntre timp, cantareste untul, siropul si zaharurile intr-o cratita si adauga 1/4 lingurita de sare. Incalzeste pana se topeste untul si se dizolva zaharul, amestecand pana devine neted. Scoate de pe foc si raceste 10 minute. Reduce cuptorul la 160C/140C ventilator/gaz 3.\n\nBate ouale intr-un bol. Adauga amestecul de sirop, vanilia si nucile pecan si amesteca bine. Toarna jumatate din amestec in forma de tarta, presara jumatate din bucatile de ciocolata, apoi acopera cu restul de umplutura si ciocolata. Coace pe raftul din mijloc 50-55 minute pana se intareste. Scoate din cuptor si lasa sa se raceasca, apoi pune la rece cel putin 2 ore inainte de servire.',
'ru': 'Сначала приготовьте тесто. Положите ингредиенты в кухонный комбайн с 1/4 чайной ложки соли. Измельчите до состояния крошки. Влейте 2-3 чайные ложки холодной воды через воронку при работающем лезвии - смесь должна начать собираться. Выложите на рабочую поверхность и соберите, кратко вымешивая в шар. Сплющите в диск, заверните в плёнку и охладите минимум 20 минут. Разогрейте духовку до 200C/180C вентилятор/газ 6.\n\nДостаньте тесто из холодильника и оставьте при комнатной температуре на 5 минут для размягчения. Посыпьте рабочую поверхность мукой, разверните тесто и раскатайте в круг толщиной с монету. Выложите тестом глубокую рифлёную круглую форму 23cm - моя была около 3cm глубиной. Прижмите тесто в углы и по бокам, убедившись, что нет зазоров. Оставьте 1cm теста свисающим (сохраните обрезки на потом). Выстелите пергаментом (сомните его сначала для гибкости) и заполните бобами для выпечки. Выпекайте вслепую 15-20 минут, пока бока не схватятся, затем уберите пергамент и бобы и верните в духовку на 5 минут до золотистого цвета. Обрежьте тесто вровень с краем формы - маленький зубчатый нож лучше всего. Если есть трещины, залатайте обрезками.\n\nТем временем взвесьте масло, сироп и сахара в кастрюлю и добавьте 1/4 чайной ложки соли. Нагрейте до таяния масла и растворения сахара, помешивая до гладкости. Снимите с огня и остудите 10 минут. Уменьшите температуру до 160C/140C вентилятор/газ 3.\n\nВзбейте яйца в миске. Добавьте сиропную смесь, ваниль и орехи пекан и хорошо перемешайте. Влейте половину смеси в форму, рассыпьте половину шоколадных кусочков, затем покройте оставшейся начинкой и шоколадом. Выпекайте на среднем ярусе 50-55 минут до застывания. Достаньте из духовки и остудите, затем охладите минимум 2 часа перед подачей.',
'es': 'Primero, prepare la masa. Ponga los ingredientes en un procesador de alimentos con 1/4 de cucharadita de sal. Pulse hasta que la mezcla parezca migas de pan. Rocee 2-3 cucharaditas de agua fria por el embudo mientras la cuchilla gira - la mezcla deberia empezar a agruparse. Ponga sobre la superficie de trabajo y una, amasando brevemente en una bola. Aplane en un disco, envuelva en plastico adherente y refrigere por al menos 20 minutos. Caliente el horno a 200C/180C ventilador/gas 6.\n\nSaque la masa del refrigerador y deje a temperatura ambiente por 5 minutos para ablandar. Enharinela superficie de trabajo, desenvuelva la masa y estire en un circulo del grosor de una moneda. Forre un molde redondo acanalado profundo de 23cm - el mio tenia unos 3cm de profundidad. Presione la masa en las esquinas y los lados, asegurandose de que no haya huecos. Deje 1cm de masa sobrante (guarde recortes para despues). Forre con papel pergamino (arrugelo primero para hacerlo mas flexible) y llene con frijoles para hornear. Hornee a ciegas por 15-20 minutos hasta que los lados esten firmes, luego retire el pergamino y los frijoles y regrese al horno por 5 minutos hasta que este dorado. Recorte la masa al ras del borde del molde - un cuchillo pequeno de sierra es mejor. Si hay grietas, reparelas con los recortes.\n\nMientras tanto, pese la mantequilla, el jarabe y los azucares en una olla y agregue 1/4 de cucharadita de sal. Caliente hasta que la mantequilla se derrita y el azucar se disuelva, revolviendo hasta que quede suave. Retire del fuego y enfrie por 10 minutos. Reduzca el horno a 160C/140C ventilador/gas 3.\n\nBata los huevos en un tazon. Agregue la mezcla de jarabe, la vainilla y las nueces pecanas y mezcle bien. Vierta la mitad de la mezcla en el molde, esparza la mitad de las chispas de chocolate, luego cubra con el relleno y chocolate restantes. Hornee en la rejilla media por 50-55 minutos hasta que cuaje. Retire del horno y deje enfriar, luego refrigere al menos 2 horas antes de servir.',
}

# 53320: Chocolate alfajores
translations_p4['53320'] = {
'ro': 'Pentru biscuiti, bate untul cu zaharul cateva minute. Apoi adauga oul si mierea si amesteca bine. Adauga faina, amidonul de porumb, cacaoa, bicarbonatul de sodiu si praful de copt si amesteca pana obtii un aluat. Inveleste in folie alimentara si pune la rece cel putin o jumatate de ora sau peste noapte.\n\n2\nTapeteaza doua tavi cu hartie de copt, preincalzeste cuptorul la 200 grade Celsius.\n\n3\nImparte aluatul in doua parti, pune o parte inapoi la frigider inainte de folosire. Intinde a doua parte la circa 2 milimetri si taie biscuiti rotunzi cu diametrul de 5-6 centimetri. Se poate face cu o forma de biscuiti sau un pahar. Ar trebui sa obtii 30 de biscuiti in total sau chiar mai multi, eu obtin circa 40. Coace o tava la un moment dat circa 8-10 minute. Lasa biscuitii sa se raceasca.\n\n4\nPentru umplutura, cauta doi biscuiti de aceeasi marime si pune circa o lingurita de dulce de leche pe cel de jos inainte de a-i lipi.\n\n5\nToaca ciocolata semiamara si topeste-o cu unt si coaja de portocala la foc mic. Inmoaie fiecare sandvis de biscuiti in ciocolata si lasa sa se raceasca pe hartie de copt inainte de servire.',
'ru': 'Для печенья взбейте масло с сахаром несколько минут. Затем добавьте яйцо и мёд и хорошо перемешайте. Добавьте муку, кукурузный крахмал, какао, соду и разрыхлитель и перемешайте до получения теста. Заверните в плёнку и охладите минимум полчаса или на ночь.\n\n2\nЗастелите два противня пергаментом, разогрейте духовку до 200 градусов Цельсия.\n\n3\nРазделите тесто на две части, одну верните в холодильник. Раскатайте вторую часть до толщины около 2 миллиметров и вырежьте круглое печенье диаметром 5-6 сантиметров. Это можно сделать формочкой или стаканом. Должно получиться 30 штук или больше, у меня обычно около 40. Выпекайте по одному противню около 8-10 минут. Остудите печенье.\n\n4\nДля начинки подберите два печенья одинакового размера и положите примерно чайную ложку дульсе де лече на нижнее, затем соедините.\n\n5\nНарежьте полусладкий шоколад и растопите с маслом и апельсиновой цедрой на слабом огне. Окуните каждый сэндвич из печенья в шоколад и дайте остыть на пергаменте перед подачей.',
'es': 'Para las galletas, bata la mantequilla con el azucar por unos minutos. Luego agregue el huevo y la miel y mezcle bien. Agregue la harina, la maicena, el cacao, el bicarbonato de sodio y el polvo de hornear y mezcle hasta obtener una masa. Envuelva en plastico adherente y refrigere por al menos media hora o toda la noche.\n\n2\nForre dos bandejas con papel pergamino, precaliente el horno a 200 grados Celsius.\n\n3\nDivida la masa en dos partes, ponga una parte de vuelta en el refrigerador antes de usar. Estire la segunda parte a unos 2 milimetros y corte galletas redondas de 5-6 centimetros de diametro. Esto se puede hacer con un cortador de galletas o un vaso. Deberia obtener 30 galletas en total o incluso mas, yo obtengo unas 40. Hornee una bandeja a la vez por unos 8-10 minutos. Deje enfriar las galletas.\n\n4\nPara el relleno, busque dos galletas del mismo tamano y ponga aproximadamente una cucharadita de dulce de leche en la de abajo antes de unirlas.\n\n5\nPique el chocolate semiamargo y derritaloa con mantequilla y ralladura de naranja a fuego lento. Sumerja cada galleta sandwich en el chocolate y deje enfriar sobre papel pergamino antes de servir.',
}

# 52853: Chocolate Avocado Mousse
translations_p4['52853'] = {
'ro': '1. Amesteca toate ingredientele de mousse in robotul de bucatarie pana devine neted. Adauga pudra de cacao prima si, pe masura ce amesteci, tine toate ingredientele la indemana pentru a ajusta proportiile usor, deoarece marimea avocado si bananelor variaza mult. Proportia perfecta pentru a evita sa aiba gust prea puternic de unul sau altul este sa folosesti cantitati egale din ambele.\n\n2. Gusteaza si adauga cateva picaturi de stevia daca simti ca ai nevoie de mai multa dulceata.\n\n3. Umple cesti mici sau pahare cu mousse-ul, presara pudra de cacao sau bucatele si serveste.\n\nSfat: Daca nu ai o banana congelata la indemana, poti folosi una normala si apoi raceste mousse-ul inainte de servire pentru un desert racoritor.',
'ru': '1. Смешайте все ингредиенты мусса в кухонном комбайне до однородности. Сначала добавьте какао-порошок и по мере смешивания держите все ингредиенты под рукой для корректировки пропорций, так как размер авокадо и бананов сильно варьируется. Идеальная пропорция, чтобы блюдо не имело слишком выраженного вкуса одного или другого, - использовать равные количества обоих.\n\n2. Попробуйте и добавьте несколько капель стевии, если чувствуете, что нужно больше сладости.\n\n3. Наполните маленькие чашки или стопки муссом, посыпьте какао-порошком или крупкой и подавайте.\n\nСовет: Если у вас нет замороженного банана, можно использовать обычный и охладить мусс перед подачей для освежающего десерта.',
'es': '1. Licue todos los ingredientes del mousse en su procesador de alimentos hasta que quede suave. Agregue el cacao en polvo primero y, mientras mezcla, tenga todos los ingredientes a mano para ajustar las proporciones ligeramente, ya que el tamano de los aguacates y platanos varia mucho. La proporcion perfecta para evitar que el plato sepa demasiado a uno u otro es usar cantidades iguales de ambos.\n\n2. Pruebe y agregue unas gotas de stevia si siente que necesita mas dulzura.\n\n3. Llene tazas pequenas o vasos de shot con el mousse, espolvoree con cacao en polvo o trozos y sirva.\n\nConsejo: Si no tiene un platano congelado a mano, puede usar uno normal y luego refrigerar el mousse antes de servir para un postre refrescante.',
}

# 52966: Chocolate Caramel Crispy
translations_p4['52966'] = {
'ro': 'Unge si tapeteaza o tava de copt de 20 x 20cm cu hartie de copt.\nPune batoanele Mars si untul intr-un bol rezistent la caldura si aseaza peste o cratita cu apa care fierbe usor. Amestecand cu un tel, topeste pana amestecul devine neted.\nToarna peste Rice Krispies intr-un bol de amestecat si amesteca pana toate ingredientele sunt combinate uniform. Apasa uniform in tava pregatita si pune deoparte.\nTopeste ciocolata cu lapte la microunde sau peste o cratita cu apa care fierbe usor.\nIntinde ciocolata topita peste amestecul de Rice Krispies si lasa sa se intareasca intr-un loc racoros. Dupa ce s-a intarit, taie in patrate si serveste!',
'ru': 'Смажьте и застелите форму для выпечки 20 x 20cm пергаментом.\nПоложите батончики Mars и масло в жаропрочную миску и поставьте над кастрюлей с едва кипящей водой. Помешивая венчиком, растопите до однородности.\nПолейте рисовые хлопья в миске и перемешайте до равномерного распределения всех ингредиентов. Равномерно утрамбуйте в подготовленную форму и отставьте.\nРастопите молочный шоколад в микроволновке или над кастрюлей с едва кипящей водой.\nРаспределите растопленный шоколад поверх смеси из рисовых хлопьев и дайте застыть в прохладном месте. После застывания нарежьте квадратиками и подавайте!',
'es': 'Engrase y forre un molde de 20 x 20cm con papel pergamino.\nPonga las barras Mars y la mantequilla en un tazon resistente al calor y coloque sobre una olla con agua apenas hirviendo. Mezclando con un batidor, derrita hasta que la mezcla quede suave.\nVierta sobre los Rice Krispies en un tazon y mezcle hasta que todos los ingredientes esten combinados uniformemente. Presione uniformemente en el molde preparado y reserve.\nDerrita el chocolate con leche en el microondas o sobre una olla con agua apenas hirviendo.\nExtienda el chocolate derretido sobre la mezcla de Rice Krispies y deje enfriar en un lugar fresco. Una vez firme, corte en cuadros y sirva!',
}

# 53170: Chocolate churros
translations_p4['53170'] = {
'ro': 'Pasul 1\nPentru sos, pune zaharul si untul intr-o cratita si adu la fierbere pana se topeste zaharul, apoi amesteca smantana si fierbe pana obtii un sos neted, circa 2-3 minute. Scoate de pe foc, amesteca un varf de sare de mare si ciocolata si continua sa amesteci 2-3 minute, sau pana s-a topit complet. Tine cald sau lasa sa se raceasca pentru reincalzire mai tarziu. Pentru acoperire, amesteca zaharul cu scortisoara si un varf mic de sare fina de mare si pune deoparte.\n\nPasul 2\nPentru churros, pune faina, cacaoa, praful de copt si un varf generos de sare intr-un bol. Adauga extractul de vanilie si untul topit, apoi toarna cu grija 250-300ml apa clocotita si amesteca cu un tel pentru a obtine un aluat neted, foarte gros. Lasa sa se raceasca cateva minute, apoi pune amestecul intr-un pos cu dui stea mediu.\n\nPasul 3\nToarna ulei de floarea soarelui intr-o friteuza conform instructiunilor producatorului, sau intr-o oala cu fund gros, asigurandu-te ca nu este umpluta mai mult de o treime. Incinge la 170C, sau pana cand un cub de paine se rumeneste in 30 secunde. Formeaza lungimi de 12-15cm de aluat direct in ulei, taiand capatul fiecaruia cu o foarfeca pe masura. Formeaza patru sau cinci la un moment dat si gateste circa 4 minute, sau pana sunt aurii si crocanti, intorcandu-le cu un cleste pe masura ce se gatesc. Scoate din ulei si aseaza pe un gratar. Repeta cu restul aluatului. Lasa sa se raceasca daca reincalzesti mai tarziu, altfel rostogoleste churros in zaharul cu scortisoara si serveste imediat cu sosul de ciocolata cald si inghetata. Pentru reincalzire, pune pe o tava si coace 5-8 minute, apoi rostogoleste in acoperirea de zahar. Intre timp, incalzeste sosul intr-o tigaie si serveste alaturi pentru inmuiere.',
'ru': 'Шаг 1\nДля соуса положите сахар и масло в кастрюлю и доведите до кипения, пока сахар не растает, затем вмешайте сливки и варите до получения гладкого соуса, около 2-3 минут. Снимите с огня, вмешайте щепотку морской соли и шоколад и продолжайте помешивать 2-3 минуты до полного расплавления. Держите тёплым или остудите для разогрева позже. Для обсыпки смешайте сахар с корицей и маленькой щепоткой мелкой морской соли и отставьте.\n\nШаг 2\nДля чуррос насыпьте муку, какао, разрыхлитель и щедрую щепотку соли в миску. Добавьте ванильный экстракт и растопленное масло, затем осторожно влейте 250-300ml кипятка и быстро взбейте до получения гладкого, очень густого теста. Дайте остыть несколько минут, затем переложите в кондитерский мешок со средней звёздочной насадкой.\n\nШаг 3\nНалейте подсолнечное масло во фритюрницу согласно инструкции производителя или в кастрюлю с толстым дном, заполнив не более чем на треть. Нагрейте до 170C или пока кубик хлеба не подрумянится за 30 секунд. Выдавите полоски теста длиной 12-15cm прямо в масло, отрезая конец каждой ножницами. Выдавливайте по четыре-пять штук и жарьте около 4 минут до золотистого и хрустящего состояния, переворачивая щипцами. Достаньте из масла на решётку. Повторите с остальным тестом. Остудите если разогреваете позже, иначе обваляйте чуррос в коричном сахаре и подавайте немедленно с тёплым шоколадным соусом и мороженым. Для разогрева положите на противень и запекайте 5-8 минут, затем обваляйте в сахарной обсыпке. Тем временем подогрейте соус в сковороде и подавайте рядом для макания.',
'es': 'Paso 1\nPara la salsa, ponga el azucar y la mantequilla en una cacerola y lleve a fuego lento hasta que el azucar se derrita, luego incorpore la crema y cocine a fuego lento hasta tener una salsa suave, unos 2-3 minutos. Retire del fuego, incorpore una pizca de sal de mar y el chocolate y siga revolviendo 2-3 minutos o hasta que se derrita completamente. Mantenga tibio o deje enfriar para recalentar despues. Para la cobertura, mezcle el azucar con la canela y una pizca pequena de sal de mar fina y reserve.\n\nPaso 2\nPara los churros, ponga la harina, el cacao, el polvo de hornear y una pizca generosa de sal en un tazon. Agregue el extracto de vainilla y la mantequilla derretida, luego vierta con cuidado 250-300ml de agua hirviendo y bata para hacer una masa suave y muy espesa. Deje enfriar unos minutos, luego pase la mezcla a una manga pastelera con boquilla de estrella mediana.\n\nPaso 3\nVierta aceite de girasol en una freidora siguiendo las instrucciones del fabricante, o en una olla de fondo grueso sin llenar mas de un tercio. Caliente a 170C o hasta que un cubo de pan se dore en 30 segundos. Forme tiras de 12-15cm de masa directamente en el aceite, cortando el extremo con tijeras. Haga cuatro o cinco a la vez y cocine unos 4 minutos hasta que esten dorados y crujientes, volteandolos con pinzas. Retire del aceite y coloque sobre una rejilla. Repita con el resto de la masa. Deje enfriar si va a recalentar despues, de lo contrario ruede los churros en el azucar con canela y sirva inmediatamente con la salsa de chocolate tibia y helado. Para recalentar, ponga en una bandeja y hornee 5-8 minutos, luego ruede en la cobertura de azucar. Mientras tanto, caliente la salsa en una sarten y sirva al lado para mojar.',
}

# 53101: Chocolate Coconut Squares
translations_p4['53101'] = {
'ro': 'Pasul 1\nIncinge cuptorul la 180C/ventilator 160C/gaz 4. Unge cu unt si tapeteaza fundul unei tavi patrate de 20cm. Bate untul cu zaharul pana devine pal si cremos, apoi bate ouale. Adauga 1 lingura de faina daca amestecul incepe sa se taie.\n\nPasul 2\nCerne faina, praful de copt si cacaoa si incorporeaza cu o lingura metalica. Adauga laptele. Pune amestecul in tava si niveleaza. Coace 18-20 minute sau pana cand prajitura revine cand e apasata. Lasa sa se raceasca in tava.\n\nPasul 3\nPentru glazura, pune ciocolata, untul si 4 linguri de apa intr-o cratita si incalzeste usor pana se topeste. Lasa sa se raceasca putin, apoi bate zaharul pudra.\n\nPasul 4\nScoate prajitura din tava si curata hartia. Taie in 16 patrate. Inmoaie patratele in glazura, apoi rostogoleste-le in cocos. Lasa sa se intareasca pe un gratar.',
'ru': 'Шаг 1\nРазогрейте духовку до 180C/вентилятор 160C/газ 4. Смажьте маслом и застелите дно квадратной формы 20cm. Взбейте масло с сахаром до бледного и кремообразного состояния, затем вбейте яйца. Добавьте 1 столовую ложку муки, если смесь начнёт расслаиваться.\n\nШаг 2\nПросейте муку, разрыхлитель и какао и аккуратно вмешайте металлической ложкой. Добавьте молоко. Выложите смесь в форму и разровняйте. Выпекайте 18-20 минут или пока пирожное не пружинит при нажатии. Остудите в форме.\n\nШаг 3\nДля глазури положите шоколад, масло и 4 столовые ложки воды в кастрюлю и осторожно нагрейте до расплавления. Слегка остудите, затем вмешайте сахарную пудру.\n\nШаг 4\nДостаньте пирожное из формы и снимите бумагу. Нарежьте на 16 квадратиков. Окуните квадратики в глазурь, затем обваляйте в кокосовой стружке. Дайте застыть на решётке.',
'es': 'Paso 1\nCaliente el horno a 180C/ventilador 160C/gas 4. Engrase y forre la base de un molde cuadrado de 20cm. Bata la mantequilla con el azucar hasta que quede palida y cremosa, luego agregue los huevos. Agregue 1 cucharada de harina si la mezcla empieza a cortarse.\n\nPaso 2\nTamice la harina, el polvo de hornear y el cacao e incorpore con una cuchara metalica. Agregue la leche. Ponga la mezcla en el molde y nivele. Hornee 18-20 minutos o hasta que el bizcocho rebote al presionarlo. Deje enfriar en el molde.\n\nPaso 3\nPara el glaseado, ponga el chocolate, la mantequilla y 4 cucharadas de agua en una olla y caliente suavemente hasta que se derrita. Deje enfriar ligeramente, luego incorpore el azucar glass.\n\nPaso 4\nRetire el bizcocho del molde y despegue el papel. Corte en 16 cuadros. Sumerja los cuadros en el glaseado, luego ruedelos en el coco. Deje secar sobre una rejilla.',
}

# 53324: Chocolate empanadas
translations_p4['53324'] = {
'ro': 'Pentru umplutura, pune conserva intr-o oala mare si acopera complet cu apa. Fierbe doua ore si jumatate, adaugand apa din cand in cand. Lasa sa se raceasca inainte de deschidere.\n\n2\nPentru aluat, combina faina, pudra de cacao si sarea intr-un bol mare. Adauga untul rece in bucati mici si freaca cu degetele pana devine maruntisor. Adauga oul si framanta pana obtii un aluat. S-ar putea sa fie nevoie sa adaugi lapte, o lingura la un moment dat, daca e inca prea uscat. Inveleste si pune la rece cel putin o jumatate de ora sau peste noapte.\n\n3\nTapeteaza o tava cu hartie de copt si preincalzeste cuptorul la 180 grade Celsius.\n\n4\nIntinde aluatul pe o suprafata usor infainata, trebuie sa fie subtire. Taie cercuri de 12cm fie cu o forma, fie cu o farfurioara mica. Pune doua-trei lingurite de dulce de leche in mijlocul fiecarui cerc. Unge marginile cu lapte. Indoaie fiecare cerc in doua ca sa obtii o semiluna si apasa marginile cu o furculita. Poti si sa indoi marginile cu circa jumatate de centimetru in interior la fiecare centimetru pentru a crea un model.\n\n5\nAseaza empanadele pregatite pe tava si unge cu ou batut. Coace circa 20-25 minute.\n\n6\nSpre sfarsitul timpului de coacere, topeste restul de unt si amesteca zaharul cu scortisoara intr-un bol mic. Imediat ce scoti empanadele, unge-le cu untul si presara cu amestecul de zahar. Empanadele pot fi gustate calde sau reci. Daca le mananci calde, ai grija sa nu te arzi cu umplutura fierbinte!',
'ru': 'Для начинки поместите банку в большую кастрюлю и полностью залейте водой. Варите два с половиной часа, периодически доливая воду. Остудите перед открыванием.\n\n2\nДля теста смешайте муку, какао-порошок и соль в большой миске. Добавьте холодное масло маленькими кусочками и разотрите пальцами в крошку. Добавьте яйцо и замесите тесто. Возможно, придётся добавить молоко, по столовой ложке за раз, если тесто слишком сухое. Заверните и охладите минимум полчаса или на ночь.\n\n3\nЗастелите противень пергаментом и разогрейте духовку до 180 градусов Цельсия.\n\n4\nРаскатайте тесто на слегка присыпанной мукой поверхности, оно должно быть тонким. Вырежьте кружки по 12cm формочкой или маленьким блюдцем. Положите две-три чайные ложки дульсе де лече в центр каждого кружка. Смажьте края молоком. Сложите каждый кружок пополам в полумесяц и прижмите края вилкой. Можно также загибать края внутрь по полсантиметра каждый сантиметр для создания узора.\n\n5\nРазложите подготовленные эмпанадас на противне и смажьте яичной смесью. Выпекайте около 20-25 минут.\n\n6\nК концу выпечки растопите оставшееся масло и смешайте сахар с корицей в маленькой миске. Как только достанете эмпанадас, сразу смажьте маслом и посыпьте сахарной смесью. Эмпанадас можно есть как тёплыми, так и холодными. Если едите тёплыми, будьте осторожны с горячей начинкой!',
'es': 'Para el relleno, coloque la lata en una olla grande y cubra completamente con agua. Hierva por dos horas y media, agregando agua de vez en cuando. Deje enfriar antes de abrir.\n\n2\nPara la masa, combine la harina, el cacao en polvo y la sal en un tazon grande. Agregue la mantequilla fria en trozos pequenos y frote con los dedos hasta formar migas. Agregue el huevo y trabaje hasta obtener una masa. Puede que necesite agregar leche, una cucharada a la vez, si aun esta muy seca. Envuelva y refrigere por al menos media hora o toda la noche.\n\n3\nForre una bandeja con papel pergamino y precaliente el horno a 180 grados Celsius.\n\n4\nEstire la masa sobre una superficie ligeramente enharinada, debe quedar delgada. Corte circulos de 12cm con un cortador de galletas o un platito pequeno. Ponga dos o tres cucharaditas de dulce de leche en el centro de cada circulo. Unte los bordes con leche. Doble cada circulo por la mitad para obtener una media luna y presione los bordes con un tenedor. Tambien puede doblar los bordes hacia adentro medio centimetro cada centimetro para crear un patron.\n\n5\nColoque las empanadas preparadas en la bandeja y unte con huevo batido. Hornee unos 20-25 minutos.\n\n6\nHacia el final del tiempo de horneado, derrita la mantequilla restante y mezcle el azucar y la canela en un tazon pequeno. Una vez que saque las empanadas, inmediatamente unte con la mantequilla y espolvoree con la mezcla de azucar. Las empanadas se pueden disfrutar tibias o frias. Si las come tibias, tenga cuidado de no quemarse con el relleno caliente!',
}

print("Phase 4 translations defined")
