#!/usr/bin/env python3
"""Part 5: Remaining recipe translations"""

translations_p5 = {}

# 52776: Chocolate Gateau
translations_p5['52776'] = {
'ro': 'Preincalzeste cuptorul la 180°C/350°F/gaz 4. Unge si tapeteaza fundul unei forme rotunde de 20cm cu arc si hartie de copt.\nRupe ciocolata intr-un bol rezistent la caldura si aseaza peste o cratita cu apa care fierbe usor si amesteca pana se topeste. (sau topeste la microunde 2-3 minute amestecand din cand in cand)\nPune untul si zaharul intr-un bol si bate cu o lingura de lemn pana devine deschis si pufos. Bate treptat ouale, adaugand putin faina daca amestecul incepe sa se taie. Incorporeaza restul de faina cu ciocolata topita racita si laptele. Amesteca pana devine neted.\nIntinde amestecul in forma si coace 50-55 minute sau pana e ferm in centru si o scobitoare iese curata. Raceste 10 minute, apoi rastoarna si raceste complet.',
'ru': 'Разогрейте духовку до 180°C/350°F/газ 4. Смажьте и застелите дно круглой разъёмной формы 20cm пергаментом.\nРазломайте шоколад в жаропрочную миску, поставьте над кастрюлей с едва кипящей водой и помешивайте до расплавления. (или растопите в микроволновке 2-3 минуты, периодически помешивая)\nПоложите масло и сахар в миску и взбейте деревянной ложкой до светлого и пышного состояния. Постепенно вбейте яйца, добавляя немного муки, если смесь начнёт расслаиваться. Аккуратно вмешайте оставшуюся муку с остывшим растопленным шоколадом и молоком. Размешайте до однородности.\nВыложите смесь в форму и выпекайте 50-55 минут или до твёрдости в центре и чистой шпажки. Остудите 10 минут, затем извлеките и полностью остудите.',
'es': 'Precaliente el horno a 180°C/350°F/gas 4. Engrase y forre la base de un molde redondo desmontable de 20cm con papel pergamino.\nRompa el chocolate en un tazon resistente al calor y coloque sobre una olla con agua apenas hirviendo y revuelva hasta que se derrita. (o derrita en el microondas por 2-3 minutos revolviendo de vez en cuando)\nPonga la mantequilla y el azucar en un tazon y bata con una cuchara de madera hasta que quede claro y esponjoso. Bata gradualmente los huevos, agregando un poco de harina si la mezcla empieza a cortarse. Incorpore la harina restante con el chocolate derretido enfriado y la leche. Mezcle hasta que quede suave.\nExtienda la mezcla en el molde y hornee 50-55 minutos o hasta que este firme en el centro y un palillo salga limpio. Enfrie por 10 minutos, luego desmolde y enfrie completamente.',
}

# 52860: Chocolate Raspberry Brownies
translations_p5['52860'] = {
'ro': 'Incinge cuptorul la 180C/160C ventilator/gaz 4. Tapeteaza o tava de 20 x 30cm cu hartie de copt. Pune ciocolata, untul si zaharul intr-o cratita si topeste usor, amestecand din cand in cand cu o lingura de lemn. Scoate de pe foc.\nAmesteca ouale, unul cate unul, in amestecul de ciocolata topita. Cerne faina si cacaoa deasupra si amesteca. Incorporeaza jumatate din zmeura, pune in tava, apoi imprastie restul de zmeura deasupra. Coace pe raftul din mijloc 30 minute sau, daca preferi o textura mai ferma, inca 5 minute. Raceste inainte de a taia in patrate. Pastreaza intr-un recipient etans pana la 3 zile.',
'ru': 'Разогрейте духовку до 180C/160C вентилятор/газ 4. Застелите форму 20 x 30cm пергаментом. Положите шоколад, масло и сахар в кастрюлю и осторожно растопите, периодически помешивая деревянной ложкой. Снимите с огня.\nВмешайте яйца по одному в растопленную шоколадную смесь. Просейте муку и какао сверху и перемешайте. Вмешайте половину малины, выложите в форму, затем рассыпьте оставшуюся малину сверху. Выпекайте на среднем ярусе 30 минут или, если предпочитаете более плотную текстуру, ещё 5 минут. Остудите перед нарезкой на квадратики. Храните в герметичном контейнере до 3 дней.',
'es': 'Caliente el horno a 180C/160C ventilador/gas 4. Forre una bandeja de 20 x 30cm con papel pergamino. Ponga el chocolate, la mantequilla y el azucar en una olla y derrita suavemente, revolviendo de vez en cuando con una cuchara de madera. Retire del fuego.\nIncorpore los huevos, uno por uno, en la mezcla de chocolate derretido. Tamice la harina y el cacao encima y revuelva. Incorpore la mitad de las frambuesas, vierta en la bandeja, luego esparza las frambuesas restantes encima. Hornee en la rejilla media por 30 minutos o, si prefiere una textura mas firme, por 5 minutos mas. Enfrie antes de cortar en cuadros. Guarde en un recipiente hermetico hasta por 3 dias.',
}

# 52905: Chocolate Souffle
translations_p5['52905'] = {
'ro': 'Incinge cuptorul la 220C/ventilator 200C/gaz 7 si aseaza o tava pe raftul de sus. Pentru sos, incalzeste smantana si zaharul pana fierb. Scoate de pe foc, amesteca ciocolata si untul pana se topesc, apoi tine cald.\nUnge 6 ramekinuri de 150ml cu unt topit, presara cu cele 2 linguri de zahar pudra fin, apoi rastoarna excesul. Topeste ciocolata si smantana intr-un bol peste o cratita cu apa care fierbe, raceste, apoi amesteca galbenusurile. Bate albusurile pana isi tin forma, apoi adauga zaharul, 1 lingura la un moment dat, batand inapoi la aceeasi consistenta. Amesteca o lingura in ciocolata, apoi incorporeaza usor restul.\nLucrand rapid, umple ramekinurile, sterge marginile si trece degetul mare pe margini. Reduce cuptorul la 200C/ventilator 180C/gaz 6, aseaza ramekinurile pe tava si coace 8-10 minute pana cresc cu o usoara oscilare. Nu deschide usa cuptorului prea devreme ca s-ar putea sa cada.\nCand sufleurile sunt gata, presara zahar pudra, scoate o gaura mica din varf, apoi toarna putin sos de ciocolata fierbinte. Pune capacele la loc si serveste imediat.',
'ru': 'Разогрейте духовку до 220C/вентилятор 200C/газ 7 и поставьте противень на верхнюю полку. Для соуса нагрейте сливки и сахар до кипения. Снимите с огня, вмешайте шоколад и масло до расплавления, затем держите тёплым.\nСмажьте 6 формочек по 150ml растопленным маслом, посыпьте 2 столовыми ложками мелкого сахара, затем стряхните излишки. Растопите шоколад и сливки в миске над кастрюлей с кипящей водой, остудите, затем вмешайте желтки. Взбейте белки до устойчивых пиков, затем добавляйте сахар по 1 столовой ложке, взбивая до прежней консистенции. Вмешайте ложку в шоколад, затем аккуратно вмешайте остальное.\nРаботая быстро, наполните формочки, протрите края и проведите большим пальцем по краям. Уменьшите духовку до 200C/вентилятор 180C/газ 6, поставьте формочки на противень и выпекайте 8-10 минут до поднятия с лёгким покачиванием. Не открывайте дверцу духовки слишком рано, иначе могут опасть.\nКогда суфле готовы, посыпьте сахарной пудрой, выскребите маленькое углубление сверху и влейте немного горячего шоколадного соуса. Верните крышечки на место и подавайте немедленно.',
'es': 'Caliente el horno a 220C/ventilador 200C/gas 7 y coloque una bandeja en la rejilla superior. Para la salsa, caliente la crema y el azucar hasta que hiervan. Retire del fuego, incorpore el chocolate y la mantequilla hasta que se derritan, luego mantenga tibio.\nUnte 6 ramequines de 150ml con mantequilla derretida, espolvoree con las 2 cucharadas de azucar fino, luego voltee para sacar el exceso. Derrita el chocolate y la crema en un tazon sobre una olla con agua hirviendo, enfrie, luego mezcle las yemas. Bata las claras hasta que mantengan su forma, luego agregue el azucar, 1 cucharada a la vez, batiendo hasta la misma consistencia. Mezcle una cucharada en el chocolate, luego incorpore suavemente el resto.\nTrabajando rapidamente, llene los ramequines, limpie los bordes y pase el pulgar alrededor de los bordes. Reduzca el horno a 200C/ventilador 180C/gas 6, coloque los ramequines en la bandeja y hornee 8-10 minutos hasta que suban con un ligero tambaleo. No abra la puerta del horno muy temprano ya que podrian colapsar.\nUna vez que los souffles esten listos, espolvoree con azucar glass, saque un pequeno hueco de la parte superior y vierta un poco de salsa de chocolate caliente. Recoloque las tapas y sirva de inmediato.',
}

# 53289: Chorba Hamra bel Frik
translations_p5['53289'] = {
'ro': 'Pune freekeh intr-un bol mic si acopera cu apa rece. Pune deoparte.\n\nCombina mielul, ceapa, piperul negru, boia, scortisoara si sarea intr-o oala. Amesteca uleiul, jumatate din coriandru, jumatate din menta si telina pana se combina. Fierbe la foc mic 15 minute. Amesteca naut-ul; toarna suficienta apa sa acopere si adu la foc mic din nou. Adauga dovlecelul, morcovul si pasta de tomate.\n\nAseaza un abur peste oala; adauga rosiile. Acopera si abure rosiile pana se inmoaie, circa 5 minute. Zdrobeste rosiile cu o lingura de lemn, lasand pulpa sa picure in supa. Scoate aburul si arunca cojile ramase.\n\nAdauga cartofii in supa si suficienta apa sa acopere. Fierbe la foc mic pana cartofii sunt moi, circa 10 minute.\n\nScurge freekeh si adauga in supa. Fierbe la foc mic pana se inmoaie, circa 15 minute. Scoate telina si arunca. Presara supa cu restul de coriandru si restul de menta inainte de servire.',
'ru': 'Положите фрике в маленькую миску и залейте холодной водой. Отставьте.\n\nСоедините баранину, лук, чёрный перец, паприку, корицу и соль в кастрюле. Вмешайте масло, половину кинзы, половину мяты и стебель сельдерея до объединения. Тушите на слабом огне 15 минут. Добавьте нут; влейте достаточно воды, чтобы покрыть, и снова доведите до кипения. Добавьте кабачок, морковь и томатную пасту.\n\nУстановите пароварку над кастрюлей; добавьте помидоры. Накройте и парьте помидоры до мягкости, около 5 минут. Раздавите помидоры деревянной ложкой, чтобы мякоть стекала в суп. Уберите пароварку и выбросьте оставшуюся кожуру.\n\nДобавьте картофель в суп и достаточно воды, чтобы покрыть. Тушите, пока картофель не станет мягким, около 10 минут.\n\nСлейте фрике и добавьте в суп. Тушите до мягкости, около 15 минут. Достаньте стебель сельдерея и выбросьте. Посыпьте суп оставшейся кинзой и мятой перед подачей.',
'es': 'Coloque el freekeh en un tazon pequeno y cubra con agua fria. Reserve.\n\nCombine el cordero, la cebolla, la pimienta negra, el pimenton, la canela y la sal en una olla. Incorpore el aceite, la mitad del cilantro, la mitad de la menta y el tallo de apio hasta combinar. Cocine a fuego lento por 15 minutos. Incorpore los garbanzos; vierta suficiente agua para cubrir y regrese a fuego lento. Agregue el calabacin, la zanahoria y la pasta de tomate.\n\nColoque una vaporera sobre la olla; agregue los tomates. Cubra y cocine al vapor hasta que esten suaves, unos 5 minutos. Aplaste los tomates con una cuchara de madera, dejando que la pulpa gotee en la sopa. Retire la vaporera y deseche las cascaras sobrantes.\n\nAgregue la papa a la sopa y suficiente agua para cubrir. Cocine a fuego lento hasta que la papa este suave, unos 10 minutos.\n\nEscurra el freekeh y agregue a la sopa. Cocine a fuego lento hasta que este suave, unos 15 minutos. Retire el tallo de apio y deseche. Espolvoree la sopa con el cilantro y la menta restantes antes de servir.',
}

# 53136: Choripan
translations_p5['53136'] = {
'ro': 'La gratar chorizo: Gateste chorizo pe gratar sau intr-o tigaie pana sunt complet gatite, circa 10-15 minute.\nPregateste chiflele: Taie chiflele si rumeneste-le usor pe gratar sau intr-o tigaie.\nAsamblare: Taie fiecare chorizo pe lungime si aseaza intr-o chifla. Adauga o cantitate generoasa de sos chimichurri deasupra.\nServeste: Savureaza imediat cat este cald.\nSfaturi:\n\nGateste chorizo incet la foc mediu pentru a preveni spargerea pielitei si pentru a se gati uniform.\nRumeneste painea pe gratar pentru a absorbi din aromele chorizo.',
'ru': 'Обжарьте чоризо на гриле: Готовьте чоризо на гриле или сковороде до полной готовности, около 10-15 минут.\nПодготовьте булочки: Разрежьте булочки и слегка подрумяньте на гриле или сковороде.\nСоберите: Разрежьте каждую чоризо вдоль и поместите в булочку. Щедро полейте соусом чимичурри сверху.\nПодавайте: Наслаждайтесь немедленно, пока горячее.\nСоветы:\n\nЖарьте чоризо медленно на среднем огне, чтобы оболочка не лопнула и прожарилось равномерно.\nПоджарьте хлеб на гриле, чтобы он впитал ароматы чоризо.',
'es': 'Ase los chorizos: Cocine los chorizos en una parrilla o sarten hasta que esten completamente cocidos, unos 10-15 minutos.\nPrepare los panes: Corte los panes y tuestelos ligeramente en la parrilla o sarten.\nArme: Corte cada chorizo a lo largo y coloque en un pan. Cubra con una cantidad generosa de salsa chimichurri.\nSirva: Disfrute inmediatamente mientras esta caliente.\nConsejos:\n\nAse el chorizo lentamente a fuego medio para evitar que se reviente la piel y asegurar una coccion uniforme.\nTueste el pan en la parrilla para que absorba los sabores del chorizo.',
}

# 53168: Chorizo & chickpea soup
translations_p5['53168'] = {
'ro': 'Pasul 1\nPune o cratita medie pe foc si adauga rosiile, urmate de o conserva de apa. In timp ce rosiile se incalzesc, toaca rapid chorizo in bucati mari (scoatand pielea) si taie varza in fasii.\n\nPasul 2\nPune chorizo si varza in cratita cu fulgii de ardei iute si naut-ul, apoi sfarama cubul de supa. Amesteca bine, acopera si lasa sa fiarba la foc mare 6 minute sau pana cand varza este frageda. Serveste in boluri cu paine crocanta sau cu usturoi.',
'ru': 'Шаг 1\nПоставьте среднюю кастрюлю на огонь и положите помидоры, затем добавьте банку воды. Пока помидоры нагреваются, быстро нарежьте чоризо крупными кусками (снимая кожицу) и нашинкуйте капусту.\n\nШаг 2\nПоложите чоризо и капусту в кастрюлю с хлопьями чили и нутом, затем раскрошите бульонный кубик. Хорошо перемешайте, накройте и дайте покипеть на сильном огне 6 минут или пока капуста не станет нежной. Разлейте по мискам и подавайте с хрустящим хлебом или чесночным хлебом.',
'es': 'Paso 1\nPonga una olla mediana al fuego y agregue los tomates, seguidos de una lata de agua. Mientras los tomates se calientan, pique rapidamente el chorizo en trozos grandes (retirando la piel) y corte el repollo en tiras.\n\nPaso 2\nAgrege el chorizo y el repollo a la olla con las hojuelas de chile y los garbanzos, luego desmenuce el cubito de caldo. Revuelva bien, cubra y deje hervir a fuego alto por 6 minutos o hasta que el repollo este tierno. Sirva en tazones con pan crujiente o pan con ajo.',
}

# 53157: Chorizo & soft-boiled egg salad
translations_p5['53157'] = {
'ro': 'Pasul 1\nGateste cartofii intr-o oala mare cu apa sarata 12 minute, adaugand ouale dupa 6 minute si fasolea in ultimele 2 minute. Scurge totul si raceste ouale sub jet de apa rece.\n\nPasul 2\nIntre timp, prajeste feliile de chorizo 1-2 minute pana incep sa devina crocante. Scoate din tigaie cu o lingura cu gauri si pune deoparte, lasand uleiul de la chorizo in tigaie. Adauga usturoiul in tigaie si caleste usor 1 minut.\n\nPasul 3\nScoate tigaia de pe foc, amesteca otetul si patrunjelul, apoi combina cu cartofii, fasolea, chorizo si condimentele. Curata ouale, taie-le in sferturi si adauga la salata.',
'ru': 'Шаг 1\nСварите картофель в большой кастрюле с подсоленной водой 12 минут, добавив яйца через 6 минут, а фасоль за последние 2 минуты. Слейте всё и остудите яйца под холодной водой.\n\nШаг 2\nТем временем обжарьте ломтики чоризо 1-2 минуты, пока не начнут хрустеть. Достаньте шумовкой и отставьте, оставив масло от чоризо в сковороде. Добавьте чеснок и обжарьте 1 минуту.\n\nШаг 3\nСнимите сковороду с огня, вмешайте уксус и петрушку, затем смешайте с картофелем, фасолью, чоризо и приправами. Очистите яйца, разрежьте на четвертинки и добавьте в салат.',
'es': 'Paso 1\nCocine las papas en una olla grande con agua con sal por 12 minutos, agregando los huevos despues de 6 minutos y los ejotes en los ultimos 2 minutos. Escurra todo y enfrie los huevos bajo agua fria corriente.\n\nPaso 2\nMientras tanto, fria las rodajas de chorizo por 1-2 minutos hasta que empiecen a ponerse crujientes. Retire de la sarten con una cuchara ranurada y reserve, dejando el aceite del chorizo en la sarten. Agregue el ajo a la sarten y cocine suavemente por 1 minuto.\n\nPaso 3\nRetire la sarten del fuego, incorpore el vinagre y el perejil, luego mezcle con las papas, los ejotes, el chorizo y el sazonador. Pele los huevos, cortelos en cuartos y agreguelos a la ensalada.',
}

# 53185: Chorizo & tomato salad
translations_p5['53185'] = {
'ro': 'Pasul 1\nPune rosiile intr-un bol cu ceapa si cimbrul. Condimenteaza, apoi stropeste cu otet si ulei. Lasa aromele sa se combine in timp ce gatesti chorizo.\n\nPasul 2\nIntr-o tigaie fierbinte si uscata, prajeste feliile de chorizo pana se rumenesc pe ambele parti. Serveste rosiile cu chorizo prajit, stropit cu putin ulei din tigaie.',
'ru': 'Шаг 1\nПоложите помидоры в миску с луком и тимьяном. Приправьте, затем полейте уксусом и маслом. Пусть ароматы смешаются, пока вы готовите чоризо.\n\nШаг 2\nНа горячей сухой сковороде обжарьте ломтики чоризо до румяности с обеих сторон. Подавайте помидоры с жареным чоризо, полив небольшим количеством масла из сковороды.',
'es': 'Paso 1\nPonga los tomates en un tazon con la cebolla y el tomillo. Sazone, luego rocee con el vinagre y el aceite. Deje que los sabores se mezclen mientras cocina el chorizo.\n\nPaso 2\nEn una sarten caliente y seca, fria las rodajas de chorizo hasta que esten doradas por ambos lados. Sirva los tomates con el chorizo frito, rociados con un poco de aceite de la sarten.',
}

# 53159: Chorizo, potato & cheese omelette
translations_p5['53159'] = {
'ro': 'Pasul 1\nGateste cartoful in apa clocotita 8-10 minute sau pana se inmoaie. Scurge si lasa sa se usuce prin abur. Incinge uleiul intr-o tigaie de omleta, adauga chorizo si gateste 2 minute. Adauga cartoful si gateste inca 5 minute pana incepe sa devina crocant. Scoate continutul tigaii, sterge tigaia si fa o omleta de 2-3 oua in aceeasi tigaie. Cand e aproape gatita, presara chorizo, cartoful, patrunjelul si branza. Impatura omleta in tigaie si gateste inca 1 minut pentru a topi branza.',
'ru': 'Шаг 1\nСварите картофель в кипящей воде 8-10 минут или до мягкости. Слейте воду и дайте обсохнуть на пару. Нагрейте масло в сковороде для омлета, добавьте чоризо и готовьте 2 минуты. Добавьте картофель и готовьте ещё 5 минут, пока не начнёт хрустеть. Выложите содержимое сковороды, протрите и приготовьте омлет из 2-3 яиц в той же сковороде. Когда почти готов, посыпьте чоризо, картофелем, петрушкой и сыром. Сложите омлет в сковороде и готовьте ещё 1 минуту, чтобы сыр расплавился.',
'es': 'Paso 1\nCocine la papa en agua hirviendo por 8-10 minutos o hasta que este tierna. Escurra y deje que se seque al vapor. Caliente aceite en una sarten para omelette, agregue el chorizo y cocine 2 minutos. Agregue la papa y cocine otros 5 minutos hasta que empiece a ponerse crujiente. Saque el contenido de la sarten, limpie la sarten y cocine una omelette de 2-3 huevos en la misma sarten. Cuando este casi cocida, esparza el chorizo, la papa, el perejil y el queso. Doble la omelette en la sarten y cocine 1 minuto mas para derretir el queso.',
}

# 52990: Christmas cake
translations_p5['52990'] = {
'ro': 'Incinge cuptorul la 160C/ventilator 140C/gaz 3. Tapeteaza fundul si marginile unei forme rotunde de 20cm cu 7,5cm adancime. Bate untul si zaharul cu un mixer electric 1-2 minute pana devine foarte cremos si pal la culoare, curatand marginile bolului la jumatate. Amesteca o lingura de faina, apoi amesteca oul batut si restul de faina alternativ, un sfert la un moment dat, batand bine de fiecare data cu o lingura de lemn. Amesteca migdalele.\n\nAdauga sherry-ul (amestecul va parea taiat), apoi adauga cojile confiate, ciresele, stafidele, nucile, coaja de lamaie, condimentele, apa de trandafiri si vanilia. Bate impreuna pentru a amesteca, apoi adauga praful de copt.\n\nPune amestecul in forma si niveleaza, facand o mica adancitura in centru. Coace 30 minute, apoi scade temperatura la 150C/ventilator 130C/gaz 2 si coace inca 2-2¼ ore, pana cand o scobitoare introdusa in mijloc iese curata. Lasa sa se raceasca in forma, apoi scoate si curata hartia. Cand e complet rece, inveleste bine in folie alimentara si folie de aluminiu pentru pastrare pana e gata de decorat. Prajitura se pastreaza mai multe luni.',
'ru': 'Разогрейте духовку до 160C/вентилятор 140C/газ 3. Застелите дно и стенки круглой формы 20cm глубиной 7,5cm. Взбейте масло и сахар электрическим миксером 1-2 минуты до очень кремового и бледного состояния, очищая стенки миски на полпути. Вмешайте ложку муки, затем чередуя добавляйте взбитое яйцо и оставшуюся муку по четверти, хорошо взбивая каждый раз деревянной ложкой. Вмешайте миндаль.\n\nДобавьте херес (смесь будет выглядеть расслоившейся), затем добавьте цукаты, вишни, изюм, орехи, цедру лимона, специи, розовую воду и ваниль. Перемешайте, затем вмешайте разрыхлитель.\n\nВыложите смесь в форму, разровняйте, сделав небольшое углубление в центре. Выпекайте 30 минут, затем снизьте температуру до 150C/вентилятор 130C/газ 2 и выпекайте ещё 2-2¼ часа, пока шпажка, вставленная в середину, не выйдет чистой. Остудите в форме, затем извлеките и снимите бумагу. Когда полностью остынет, плотно заверните в пищевую плёнку и фольгу для хранения до украшения. Торт хранится несколько месяцев.',
'es': 'Caliente el horno a 160C/ventilador 140C/gas 3. Forre la base y los lados de un molde redondo de 20cm con 7,5cm de profundidad. Bata la mantequilla y el azucar con una batidora electrica por 1-2 minutos hasta que este muy cremoso y palido, raspando los lados del tazon a la mitad. Incorpore una cucharada de harina, luego alterne el huevo batido y el resto de la harina, un cuarto a la vez, batiendo bien cada vez con una cuchara de madera. Incorpore las almendras.\n\nAgregue el jerez (la mezcla parecera cortada), luego agregue las cascaras confitadas, las cerezas, las pasas, las nueces, la ralladura de limon, las especias, el agua de rosas y la vainilla. Bata para mezclar, luego incorpore el polvo de hornear.\n\nPonga la mezcla en el molde y nivele, haciendo una ligera depresion en el centro. Hornee por 30 minutos, luego baje la temperatura a 150C/ventilador 130C/gas 2 y hornee otras 2-2¼ horas, hasta que un palillo insertado en el medio salga limpio. Deje enfriar en el molde, luego saque y retire el papel. Cuando este completamente frio, envuelva bien en plastico adherente y papel aluminio para guardar hasta que este listo para decorar. El pastel se conserva por varios meses.',
}

# Remaining recipes will be handled in part 6
print("Phase 5 translations defined")
