#!/usr/bin/env python3
"""Part 3: More recipe translations"""

translations_p3 = {}

# 53365: Chinese Orange Chicken
translations_p3['53365'] = {
'ro': 'Pregateste sosul de portocale:\nBate ingredientele pentru sos intr-un bol mediu. Pune deoparte.\n\n\nPregateste puiul:\nTaie puiul in cuburi de circa 2-3 cm. Bate ouale cu sare si piper negru intr-un bol si adauga puiul. Amesteca.\n\nIntr-un bol separat, amesteca faina si amidonul de porumb. Scoate puiul din oua cu o lingura cu gauri sau un cleste, lasand excesul de ou sa se scurga, apoi transfera in amestecul de amidon si acopera bine.\n\n\nPrajeste puiul:\nAdauga ulei intr-o tigaie mare de 25-30 cm. Incinge la foc mediu-mare pana ajunge la 175°C. Daca nu ai termometru, poti testa temperatura presarand putin faina. Daca uleiul e suficient de fierbinte, ar trebui sa sfiraie imediat.\n\nCand uleiul e fierbinte, prajeste puiul in doua serii. Uleiul s-ar putea sa nu acopere complet puiul - e in regula. Gateste 3-4 minute. Intoarce bucatile de pui si gateste pana sunt gatite complet, inca 3-4 minute. Timpul total de gatit e circa 6-8 minute.\n\nScoate cuburile de pui prajite si pune-le pe o farfurie cu servetele de hartie sa se scurga. Repeta pana cand tot puiul e gatit.\n\n\nFierbe puiul in sos:\nCand puiul e gata, toarna uleiul fierbinte si sterge tigaia. Adauga o lingura proaspata de ulei impreuna cu usturoiul si salota tocate. Gateste un minut apoi adauga sosul. Fierbe sosul pana incepe sa se ingroase.\n\nCand sosul fierbe usor, adauga puiul prajit si amesteca pentru a-l acoperi. Sosul trebuie sa continue sa se ingroase si sa se lipeasca de pui. Lasa sa fiarba inca un minut sau doua. Serveste puiul cu portocale peste orez alb gatit, garnisite cu seminte de susan si ceapa verde proaspata.\n\nTi-a placut aceasta reteta? Spune-ne cu o nota si o recenzie!\n\n\nRESTURI! Puiul cu portocale se pastreaza bine la frigider 5 zile. Reincalzeste intr-o tigaie cu putin apa la foc mic. Congeleaza puiul cu portocale pana la 3 luni, dar asigura-te ca il dezgheti inainte de reincalzire ca sa nu se lipeasca bucatile.',
'ru': 'Приготовьте апельсиновый соус:\nВзбейте ингредиенты для соуса в средней миске. Отставьте.\n\n\nПодготовьте курицу:\nНарежьте курицу кубиками примерно по 2-3 см. Взбейте яйца с солью и чёрным перцем в миске и добавьте курицу. Перемешайте.\n\nВ отдельной миске смешайте муку и кукурузный крахмал. Достаньте курицу из яиц шумовкой или щипцами, дав стечь лишнему яйцу, затем переложите в смесь крахмала и хорошо обваляйте.\n\n\nОбжарьте курицу:\nНалейте масло в большую сковороду 25-30 см. Нагрейте на средне-сильном огне до 175°C. Если нет термометра, можно проверить температуру, посыпав немного муки. Если масло достаточно горячее, мука должна сразу зашипеть.\n\nКогда масло горячее, обжарьте курицу в двух партиях. Масло может не полностью покрыть курицу - это нормально. Готовьте 3-4 минуты. Переверните кусочки и готовьте до полной готовности, ещё 3-4 минуты. Общее время готовки около 6-8 минут.\n\nДостаньте обжаренные кусочки и переложите на тарелку с бумажными полотенцами для стекания. Повторите, пока вся курица не будет готова.\n\n\nПотушите курицу в соусе:\nКогда курица готова, слейте горячее масло и протрите сковороду. Добавьте свежую столовую ложку масла с рубленым чесноком и шалотом. Готовьте минуту, затем добавьте соус. Тушите соус до загустения.\n\nКогда соус слегка закипит, добавьте жареную курицу и перемешайте для покрытия. Соус должен продолжать густеть и прилипать к курице. Потушите ещё минуту-две. Подавайте курицу в апельсиновом соусе поверх варёного белого риса, украсив кунжутными семенами и свежим зелёным луком.\n\nВам понравился этот рецепт? Дайте нам знать оценкой и отзывом!\n\n\nОСТАТКИ! Курица в апельсиновом соусе хранится в холодильнике 5 дней. Разогревайте в сковороде с небольшим количеством воды на слабом огне. Замораживайте до 3 месяцев, но обязательно разморозьте перед разогревом, чтобы кусочки не слиплись.',
'es': 'Prepare la salsa de naranja:\nBata los ingredientes de la salsa en un tazon mediano. Reserve.\n\n\nPrepare el pollo:\nCorte el pollo en cubos de unos 2-3 cm. Bata los huevos con sal y pimienta negra en un tazon y agregue el pollo. Revuelva.\n\nEn un tazon aparte, mezcle la harina y la maicena. Retire el pollo de los huevos con una cuchara ranurada o pinzas, dejando escurrir el exceso de huevo, luego pase a la mezcla de maicena y cubra bien.\n\n\nFria el pollo:\nAgregue aceite a una sarten grande de 25-30 cm. Caliente a fuego medio-alto hasta alcanzar 175°C. Si no tiene termometro, puede probar la temperatura espolvoreando un poco de harina. Si el aceite esta suficientemente caliente, debe chisporrotear inmediatamente.\n\nCuando el aceite este caliente, fria el pollo en dos tandas. El aceite podria no cubrir completamente el pollo - esta bien. Cocine por 3-4 minutos. Voltee las piezas y cocine hasta que el pollo este bien cocido, unos 3-4 minutos mas. El tiempo total de coccion es de unos 6-8 minutos.\n\nRetire los cubos de pollo frito y paselos a un plato forrado con toallas de papel para que escurran. Repita hasta que todo el pollo este cocido.\n\n\nCocine el pollo en la salsa:\nCuando el pollo este listo, deseche el aceite caliente y limpie la sarten. Agregue una cucharada fresca de aceite junto con el ajo y el chalote picados. Cocine un minuto y luego agregue la salsa. Cocine a fuego lento hasta que empiece a espesar.\n\nCuando la salsa este burbujeando ligeramente, agregue el pollo frito y revuelva para cubrir. La salsa debe continuar espesando y adherirse al pollo. Deje cocinar a fuego lento un minuto o dos mas. Sirva el pollo a la naranja sobre arroz blanco cocido, decorado con semillas de sesamo y cebolletas frescas.\n\nLe gusto esta receta? Haganoslo saber con una calificacion y resena!\n\n\nSOBRAS! El pollo a la naranja se conserva bien en el refrigerador por 5 dias. Recaliente en una sarten con un chorrito de agua a fuego lento. Congele el pollo a la naranja hasta por 3 meses, pero asegurese de descongelarlo antes de recalentar para que las piezas no se peguen.',
}

# 53372: Chinese Tomato Egg Stir Fry
translations_p3['53372'] = {
'ro': 'Poti folosi supa de pui in loc de pudra de bulion de pui. Adauga 1/4 cana de supa urmata de 2 lingurite de amidon de porumb dizolvat in 1 lingura de apa, plus sare dupa gust.\nPregatirea rosiilor:\nTaie rosiile in doua. Scoate ciotul tare care se leaga de vita. Taie fiecare jumatate in treimi egale (vei obtine 6 felii din fiecare rosie).\n\nPregateste ouale jumari moi:\nIntr-o tigaie antiaderenta rece de 20-25 cm, adauga uleiul vegetal si ouale batute. Pune focul pe mediu. Cand un strat subtire de oua incepe sa se gateasca pe fund, impinge ouale intr-o directie pentru a crea straturi de oua jumari.\n\nGateste, amestecand usor tot timpul, pana cand ouale jumari sunt aproape intarite dar inca usor umede si lucioase, 2-5 minute. Muta ouale pe o farfurie si, daca e nevoie, sterge tigaia.\n\nCaleste rosiile si condimentele:\nAdauga uleiul de susan in tigaie urmat de rosii si caleste la foc mediu pana cand rosiile se inmoaie dar nu devin papate, circa 3 minute. Adauga pudra de bulion de pui, zaharul si piperul alb. Amesteca pana se combina si zaharul si bulionul s-au dizolvat, circa 1 minut.\n\nAdauga ouale, caleste si garniseste:\nAdauga ouale inapoi in tigaie cu rosiile. Caleste circa 2 minute pentru a se incalzi si combina. Gusteaza, adaugand sare doar daca e necesar. Presara ceapa verde si serveste cu orez la abur.',
'ru': 'Можно использовать куриный бульон вместо бульонного порошка. Добавьте 1/4 стакана бульона, затем 2 чайные ложки кукурузного крахмала, растворённого в 1 столовой ложке воды, плюс соль по вкусу.\nПодготовка помидоров:\nРазрежьте помидоры пополам. Удалите жёсткую часть, соединяющую с веткой. Нарежьте каждую половинку на равные трети (из каждого помидора получится 6 долек).\n\nПриготовьте мягкую яичницу-болтунью:\nВ холодую антипригарную сковороду 20-25 см добавьте растительное масло и взбитые яйца. Включите средний огонь. Когда тонкий слой яиц начнёт схватываться на дне, сдвигайте яйца в одном направлении, создавая слои яичницы.\n\nГотовьте, осторожно помешивая всё время, пока яичница почти схватится, но останется слегка влажной и блестящей, 2-5 минут. Переложите яйца на тарелку и при необходимости протрите сковороду.\n\nОбжарьте помидоры и приправы:\nДобавьте кунжутное масло в сковороду, затем помидоры и обжаривайте на среднем огне до размягчения, но не до кашицы, около 3 минут. Добавьте бульонный порошок, сахар и белый перец. Перемешивайте до объединения и растворения сахара и бульона, около 1 минуты.\n\nДобавьте яйца, обжарьте и украсьте:\nВерните яйца в сковороду с помидорами. Обжаривайте около 2 минут для прогрева и объединения. Попробуйте, добавьте соль только при необходимости. Посыпьте зелёным луком и подавайте с рисом на пару.',
'es': 'Puede usar caldo de pollo en lugar del polvo de caldo de pollo. Agregue 1/4 taza de caldo seguido de 2 cucharaditas de maicena disuelta en 1 cucharada de agua, mas sal al gusto.\nPreparacion de los tomates:\nCorte los tomates por la mitad. Retire el tallo duro que se conecta a la rama. Corte cada mitad en tercios iguales (obtendra 6 rodajas de cada tomate).\n\nPrepare los huevos revueltos suaves:\nEn una sarten antiadherente fria de 20-25 cm, agregue el aceite vegetal y los huevos batidos. Encienda a fuego medio. Cuando una capa delgada de huevos empiece a cocinarse en el fondo, empuje los huevos en una direccion para crear capas de huevos revueltos.\n\nCocine, revolviendo suavemente todo el tiempo, hasta que los huevos revueltos esten casi cuajados pero aun ligeramente humedos y brillantes, 2-5 minutos. Pase los huevos a un plato y, si es necesario, limpie la sarten.\n\nSaltee los tomates y condimentos:\nAgregue el aceite de sesamo a la sarten seguido de los tomates y saltee a fuego medio hasta que los tomates esten suaves pero no blandos, unos 3 minutos. Agregue el polvo de caldo de pollo, el azucar y la pimienta blanca. Revuelva hasta combinar y que el azucar y el caldo se hayan disuelto, unos 1 minuto.\n\nAgregue los huevos, saltee y decore:\nRegrese los huevos a la sarten con los tomates. Saltee unos 2 minutos para calentar y combinar. Pruebe, agregando sal solo si es necesario. Espolvoree con las cebolletas y sirva con arroz al vapor.',
}

# 52910: Chinon Apple Tarts
translations_p3['52910'] = {
'ro': 'Pentru jeleul de vin rosu, pune vinul rosu, zaharul de gem, anasonul stelat, cuisoara, bastonul de scortisoara, pimentul, pastaie de vanilie despiata si semintele intr-o cratita medie. Amesteca, apoi incalzeste usor pentru a dizolva zaharul. Creste focul si fierbe 20 minute pana se reduce si devine siropos. Strecoara intr-un borcan mic sterilizat si lasa sa se raceasca complet. Se pastreaza la frigider pana la 1 luna.\n\nScoate aluatul din frigider si lasa la temperatura camerei 10 minute, apoi deruleaza-l. Incinge gratarul la maxim si cuptorul la 180C/160C ventilator/gaz 4. Taie 2 cercuri de 13cm din aluat, folosind o farfurie ca ghid, si aseaza-le pe o tava antiaderenta. Presara fiecare cerc cu 1 lingura de zahar si gratineaza 5 minute pentru caramelizare, urmarind cu atentie sa nu se arda zaharul. Scoate de sub gratar. Se poate face cu cateva ore inainte si lasa acoperit in afara frigiderului.\n\nCurata, taie in sferturi si scoate cotorul merelor, taie-le in felii subtiri de 2mm si aseaza-le deasupra aluatului. Presara restul de zahar si pune la cuptor 20-25 minute pana cand aluatul e gatit si auriu, iar merele s-au inmuiat. Scoate si lasa sa se raceasca putin. Incalzeste 3 linguri de jeleu de vin rosu intr-o tigaie mica la foc mic cu 1 lingurita de apa pentru a-l face mai fluid, apoi pensuleaza deasupra tartelor.\n\nPune crema fraiche intr-un bol, cerne zaharul pudra si cardamomul si amesteca. Ridica cu grija tartele calde pe farfurii si serveste cu crema fraiche cu cardamom.',
'ru': 'Для желе из красного вина положите вино, сахар для джема, звёздчатый анис, гвоздику, палочку корицы, душистый перец, разрезанный стручок ванили и семена в среднюю кастрюлю. Перемешайте, затем нагрейте на слабом огне для растворения сахара. Увеличьте огонь и варите 20 минут до уваривания и сиропообразного состояния. Процедите в маленькую стерилизованную банку и полностью остудите. Хранится в холодильнике до 1 месяца.\n\nДостаньте тесто из холодильника и оставьте при комнатной температуре на 10 минут, затем раскатайте. Включите гриль на максимум и духовку на 180C/160C вентилятор/газ 4. Вырежьте 2 круга по 13cm из теста, используя тарелку как направляющую, и положите на антипригарный противень. Посыпьте каждый круг 1 столовой ложкой сахара и поджарьте под грилем 5 минут для карамелизации, внимательно следя, чтобы сахар не подгорел. Достаньте из-под гриля. Можно сделать за несколько часов заранее и оставить накрытым вне холодильника.\n\nОчистите, разрежьте на четвертинки и удалите сердцевину яблок, нарежьте тонкими ломтиками по 2mm и разложите поверх теста. Посыпьте оставшимся сахаром и поставьте в духовку на 20-25 минут, пока тесто не пропечётся и не станет золотистым, а яблоки не размягчатся. Достаньте и слегка остудите. Нагрейте 3 столовые ложки желе из красного вина в маленькой кастрюле на слабом огне с 1 чайной ложкой воды для разжижения, затем смажьте верх тартов.\n\nПоложите крем-фреш в миску, просейте сахарную пудру и кардамон и перемешайте. Аккуратно переложите тёплые тарты на сервировочные тарелки и подавайте с кардамоновым крем-фрешем.',
'es': 'Para la jalea de vino tinto, ponga el vino tinto, el azucar para mermelada, el anis estrellado, el clavo, la rama de canela, la pimienta de Jamaica, la vaina de vainilla partida y las semillas en una cacerola mediana. Revuelva, luego caliente suavemente para disolver el azucar. Suba el fuego y hierva por 20 minutos hasta que se reduzca y quede almibarado. Cuele en un frasco pequeno esterilizado y deje enfriar completamente. Se conserva en el refrigerador hasta 1 mes.\n\nSaque la masa del refrigerador y deje a temperatura ambiente por 10 minutos, luego desenrolle. Caliente el grill al maximo y el horno a 180C/160C ventilador/gas 4. Corte 2 circulos de 13cm de masa, usando un plato como guia, y coloque en una bandeja antiadherente. Espolvoree cada circulo con 1 cucharada de azucar y gratine por 5 minutos para caramelizar, vigilando con cuidado que el azucar no se queme. Retire del grill. Se puede hacer con unas horas de anticipacion y dejar cubierto fuera del refrigerador.\n\nPele, corte en cuartos y descorazone las manzanas, cortelas en rodajas finas de 2mm y coloquelas sobre la masa. Espolvoree con el azucar restante y ponga en el horno por 20-25 minutos hasta que la masa este cocida y dorada y las manzanas se hayan ablandado. Retire y deje enfriar ligeramente. Caliente 3 cucharadas de jalea de vino tinto en una sarten pequena a fuego lento con 1 cucharadita de agua para hacerla mas liquida, luego pincele sobre las tartas.\n\nPonga la crema fresca en un tazon, cierna el azucar glass y el cardamomo y mezcle. Levante cuidadosamente las tartas tibias a los platos de servir y sirva con la crema fresca con cardamomo.',
}

# 53319: Chivito sandwich
translations_p3['53319'] = {
'ro': 'Pentru chiflele brioche, incalzeste laptele cu untul si melasa pana se topeste untul. Adauga apa rece si oul in acest amestec.\n\n2\nIntr-un bol mare pune faina, sarea si drojdia si amesteca. Apoi adauga amestecul de lapte si apa si amesteca cu o lingura de lemn pana se combina. Nu trebuie sa framanti aluatul, e perfect bine sa faci asta de mana cu o lingura de lemn, nu trebuie sa fie foarte minutos. Acopera cu un prosop umed si pune la frigider peste noapte.\n\n3\nA doua zi dimineata, framanta aluatul pe o suprafata bine infainata putin si taie-l in opt bucati egale. Modeleaza-le in bile si aseaza-le pe o tava tapetata cu hartie de copt. Acopera din nou cu un prosop umed si lasa sa creasca circa o ora sau pana se dubleaza in marime.\n\n4\nIncinge cuptorul la 220 grade Celsius. Unge chiflele cu lapte, smantana grasa sau ou batut si presara cu seminte de susan, daca doresti. Coace circa 15-20 minute sau pana se rumenesc. Lasa sa se raceasca.\n\n5\nPentru toppinguri, toaca ceapa si caleste-o in putin unt, lasa sa se caramelizeze, poate dura 10-15 minute, amesteca din cand in cand. Freaca fripturile cu putin usturoi apoi gratareaza sau prajeste fripturile, baconul si ouale cu sare si piper, prajeste chiflele dupa ce le-ai taiat in doua. Intinde mustar pe o jumatate de chifla, aseaza pe fiecare chivito friptura, o felie de sunca, o felie de branza, o fasie de bacon, o felie de rosie si putina salata. Pune oul prajit deasupra si stropeste generos cu chimichurri si ceapa chiar inainte de servire.',
'ru': 'Для булочек бриошь нагрейте молоко с маслом и патокой, пока масло не растает. Добавьте холодную воду и яйцо в эту смесь.\n\n2\nВ большую миску насыпьте муку, соль и дрожжи и перемешайте. Затем добавьте смесь молока и воды и перемешайте деревянной ложкой до объединения. Не нужно вымешивать тесто, вполне достаточно сделать это вручную деревянной ложкой, это не должно быть очень тщательным. Накройте влажным полотенцем и уберите в холодильник на ночь.\n\n3\nНа следующее утро слегка вымесите тесто на щедро посыпанной мукой поверхности и разрежьте на восемь равных частей. Сформируйте шарики и разложите на противне, застеленном пергаментом. Снова накройте влажным полотенцем и дайте подняться около часа или до удвоения в размере.\n\n4\nРазогрейте духовку до 220 градусов Цельсия. Смажьте булочки молоком, жирными сливками или яичной смесью и посыпьте кунжутными семенами по желанию. Выпекайте около 15-20 минут или до золотистого цвета. Остудите.\n\n5\nДля начинки нарежьте лук и обжарьте в небольшом количестве масла, дайте карамелизоваться, это может занять 10-15 минут, периодически помешивайте. Натрите стейки чесноком, затем пожарьте стейки, бекон и яйца с солью и перцем, поджарьте булочки после разрезания пополам. Намажьте горчицу на одну половину булочки, выложите на каждый чивито стейк, ломтик ветчины, ломтик сыра, полоску бекона, ломтик помидора и немного салата. Положите жареное яйцо сверху и щедро полейте чимичурри и луком прямо перед подачей.',
'es': 'Para los panes de brioche, caliente la leche con la mantequilla y la melaza hasta que la mantequilla se derrita. Agregue el agua fria y el huevo a esta mezcla.\n\n2\nEn un tazon grande coloque la harina, la sal y la levadura y mezcle. Luego agregue la mezcla de leche y agua y revuelva con una cuchara de madera hasta combinar. No tiene que amasar la masa, esta perfectamente bien hacerlo a mano con una cuchara de madera, no necesita ser muy minucioso. Cubra con un pano humedo y ponga en el refrigerador toda la noche.\n\n3\nA la manana siguiente, amase la masa en una superficie generosamente enharinada un poco y corte en ocho piezas iguales. Dele forma de bolitas y coloque en una bandeja forrada con papel pergamino. Cubra nuevamente con un pano humedo y deje crecer por aproximadamente una hora o hasta que duplique su tamano.\n\n4\nCaliente el horno a 220 grados Celsius. Unte los panes con leche, crema espesa o huevo batido y espolvoree con semillas de sesamo si lo desea. Hornee por unos 15-20 minutos o hasta que esten dorados. Deje enfriar.\n\n5\nPara los toppings, pique la cebolla y saltee en un poco de mantequilla, deje caramelizar, esto puede tomar de 10 a 15 minutos, revuelva de vez en cuando. Frote los filetes con un poco de ajo y luego ase o fria los filetes, el tocino y los huevos con sal y pimienta, tueste los panes despues de haberlos cortado por la mitad. Unte mostaza en una mitad del pan, coloque en cada chivito el filete, una rebanada de jamon, una rebanada de queso, una tira de tocino, una rodaja de tomate y un poco de lechuga. Coloque el huevo frito encima y rocee generosamente con chimichurri y cebolla justo antes de servir.',
}

# 53063: Chivito uruguayo
translations_p3['53063'] = {
'ro': 'Bate carnea pana devine subtire si pune-o pe un gratar sa se rumeneasca. Pune ouale, baconul si sunca la prajit.\nTaie painea in doua, pune pieptul de vita, ouale prajite, baconul, sunca, mozzarella, rosia si salata. Acopera cu cealalta jumatate de paine si serveste.',
'ru': 'Отбейте мясо до тонкого состояния и положите на решётку для обжарки. Поставьте яйца, бекон и ветчину жариться.\nРазрежьте хлеб пополам, положите грудинку, жареные яйца, бекон, ветчину, моцареллу, помидор и салат. Накройте другой половиной хлеба и подавайте.',
'es': 'Aplaste la carne hasta que quede fina y coloquela en una plancha para dorar. Ponga los huevos, el tocino y el jamon a freir.\nCorte el pan por la mitad, coloque el pecho de res, los huevos fritos, el tocino, el jamon, la mozzarella, el tomate y la lechuga. Cubra con la otra mitad del pan y sirva.',
}

print("Phase 3 translations defined")
